### ISSUE TITLE
subclassing CollectionEncoder

### ISSUE THREAD

**Issue by cmacdonald** [stanford-futuredata/ColBERT#10]
We would like to change the indexing of data in formats other than the MSMARCO passage file - for instance, indexing an iterator or a dataframe.
Most of the changes would be in CollectionEncoder:
 - _batch_passages() and _preprocess_batch() could be overridden
 - encode() is nearly fine, except `with open(self.collection) as fi:` which assumes a file. Could this be extracted to another class method?

**Comment by okhat** [comment]
Sounds like a useful change. I'm thinking of the following changes.

In __init__(), I can add:
```
self.iterator = self._initialize_iterator()
```

By default, this would just open the tsv file. But it can be overriden.

And in encode(), I can switch to using self.iterator:
```
for batch_idx, (offset, lines, owner) in enumerate(self._batch_passages(self.iterator)):
```

Let me know if this suffices.

**Comment by cmacdonald** [comment]
Yes, sounds good to me. Thanks Omar.
