### ISSUE TITLE
environment issue

### ISSUE THREAD

**Issue by foye501** [stanford-futuredata/ColBERT#104]
when I run the command of train ,the following error happend:
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by okhat** [comment]
I suggest you use the new_api branch.

If you'd like to use the main branch, you might have to update your conda_env to this file:

```name: colbert-v0.2
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip=20.2.2
  - cudatoolkit
  - pytorch=1.6.0
  - torchvision=0.7.0
  - faiss-gpu=1.6.3
  - pip:
    - mlflow
    - tensorboard
    - tqdm
    - transformers==3.0.2
    - ujson```

I just removed the version specified for the cudatoolkit.

**Comment by foye501** [comment]
Thank you  for your reply. 
I used the new_api and create a env by conda and run the command following:

CUDA_VISIBLE_DEVICES="2" \
python -m torch.distributed.launch --nproc_per_node=1 -m \
colbert.train --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
--triples /path/to/data

I get  error like 

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_glf13ztj/none_81zq2bss/attempt_3/0/error.json
/anaconda3/envs/colbert-v0.4/bin/python: No module named colbert.train

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2629127) of binary: /szzn/kuituosi/anaconda3/envs/colbert-v0.4/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish

DId I miss something?

**Comment by foye501** [comment]
Thank you  for your reply. 
I used the new_api and create a env by conda and run the command following:

CUDA_VISIBLE_DEVICES="2" \
python -m torch.distributed.launch --nproc_per_node=1 -m \
colbert.train --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
--triples /path/to/data

I get  error like 

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_glf13ztj/none_81zq2bss/attempt_3/0/error.json
/anaconda3/envs/colbert-v0.4/bin/python: No module named colbert.train

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2629127) of binary: /szzn/kuituosi/anaconda3/envs/colbert-v0.4/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish

DId I miss something?

**Comment by foye501** [comment]
just remove the version specified for cudatoolkit and faiss-gpu
