### ISSUE TITLE
Is there an implementation/possibility of an exact search in a file? (Result = exact line of the file)

### ISSUE THREAD

**Issue by lalenzos** [stanford-futuredata/ColBERT#109]
Hi,
I wanted to ask if there is a possibility or a demo code with which you can search an entire file and get exactly one line or code block as a search result?
The search behaviour should thus be similar to conventional searches, where, for example, several files are searched for a search query and only those individual lines/code blocks are returned as results where a hit was landed.

I am grateful for any ideas/suggestions/code examples. Thanks.

**Comment by okhat** [comment]
You can simply create a collection where every passage corresponds to one line of your file.

Exact search (i.e., matching exact words) is not within the scope of ColBERT, though.
