### ISSUE TITLE
Index Collections with Faiss in ColBERTv1

### ISSUE THREAD

**Issue by r1ckC139** [stanford-futuredata/ColBERT#120]
Hi team,
I have a question about index collection with Faiss in ColBERTv1, below are your two commands for running index and index faiss. So if I want to run colbert.index_faiss, I have to run colbert.index first to get a uncompress index and then run the second command to create a faiss object on top of that. right? 
![image](https://user-images.githubusercontent.com/61724310/180916233-be937845-1ac9-4206-83c6-186e1fa0365a.png)
![image](https://user-images.githubusercontent.com/61724310/180916270-b3989f9d-826f-4adc-8e6b-49edc46d1daa.png)

**Comment by okhat** [comment]
That's right! Sorry for the slow response.
