### ISSUE TITLE
Fine-tune the colbert v2 pretrained model

### ISSUE THREAD

**Issue by jiho283** [stanford-futuredata/ColBERT#121]
Thank you for sharing the pretrained model. 
I would like to use the pretrained model by fine-tuning it on our local dataset.
So, could you share the related code or command for fine-tuning?

**Comment by santhnm2** [comment]
Hi @jiho283, you can fine-tune a pre-trained model following this template:
```
from colbert.infra import Run, RunConfig, ColBERTConfig
from colbert import Trainer

if __name__=='__main__':
    with Run().context(RunConfig(nranks=4, experiment="fine-tune")):

        config = ColBERTConfig(
            bsize=32,
            root="/path/to/experiments",
        )
        trainer = Trainer(
            triples="/path/to/triples.tsv",
            queries="/path/to/queries.tsv",
            collection="/path/to/collection.tsv",
            config=config,
        )

        checkpoint_path = trainer.train(checkpoint="/path/to/pretrained_checkpoint")

        print(f"Saved checkpoint to {checkpoint_path}...")
```

**Comment by jiho283** [comment]
Thank you for sharing the code!

**Comment by r1ckC139** [comment]
Hi @santhnm2, @jiho283,
In your script above, "/path/to/experiments" is a path of a pre-trained ColBERT v1 checkpoint?

**Comment by santhnm2** [comment]
This is the path to the output directory.

**Comment by whaleloops** [comment]
Hi @santhnm2, @jiho283,
When fine-tuning, I got the following error when checkpoint is set to ColBERT v2
![image](https://user-images.githubusercontent.com/31370581/190947193-196fe550-7356-4022-ba41-61150829a296.png)

and no error when the checkpoint is 'bert-base-uncased'.

Could you also provide pre-trained ColBERT v1 checkpoint?

Thanks in advance.

**Comment by 731963709** [comment]
Hi @whaleloops 
I have the same problem as you. Have you solved it？
Thanks in advance.

**Comment by slawekgarcarz** [comment]
Did anyone solve this problem?
