### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by poorya2021** [stanford-futuredata/ColBERT#128]
Hi, dear @okhat 
I used a dataset to train the model, which contains three files after creating a checkpoint:

colbert.dnn
colbert-10000.dnn
colbert-20000.dnn

Does it matter which of the above files I use?
If I am going to use all three files, how should I apply it inside the script command?

**Comment by okhat** [comment]
You can either use the latest one (colbert.dnn) or do validation on a dev set to select the best-performing one.
