### ISSUE TITLE
Faiss indexing assertion

### ISSUE THREAD

**Issue by cmacdonald** [stanford-futuredata/ColBERT#13]
```
[Nov 29, 12:42:01] #> Processing slice #1 of 1 (range 0..24).
<snip>
[Nov 29, 13:07:41] #> Indexing the vectors...
[Nov 29, 13:07:41] #> Loading ('/local/terrier/Indices/msMarco/2020_craig/colbert_passage/index_name/0.pt', '/local/terrier/Indices/msMarco/2020_craig/colbert_passage/index_name/1.pt', '/local/terrier/Indices/msMarco/2020_craig/colbert_passage/index_name/2.pt') (from queue)...
[Nov 29, 13:08:09] #> Processing a sub_collection with shape (86536593, 128)
[Nov 29, 13:08:09] Add data with shape (86536593, 128) (offset = 0)..
  IndexIVFPQ size 0 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=0 useFloat16=1 reserveVecs=33554432
33488896/86536593 (219.002 s)   Flush indexes to CPU
Traceback (most recent call last):
  File "/users/tr.craigm/anaconda3/envs/colbert/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/users/tr.craigm/anaconda3/envs/colbert/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/users/tr.craigm/projects/pyterrier/ColBERT/colbert/index_faiss.py", line 43, in <module>
    main()
  File "/users/tr.craigm/projects/pyterrier/ColBERT/colbert/index_faiss.py", line 39, in main
    index_faiss(args)
  File "/users/tr.craigm/projects/pyterrier/ColBERT/colbert/indexing/faiss.py", line 108, in index_faiss
    index.add(sub_collection)
  File "/users/tr.craigm/projects/pyterrier/ColBERT/colbert/indexing/faiss_index.py", line 48, in add
    self.gpu.add(self.index, data, self.offset)
  File "/users/tr.craigm/projects/pyterrier/ColBERT/colbert/indexing/faiss_index_gpu.py", line 112, in add
    self._flush_to_cpu(index, nb, offset)
  File "/users/tr.craigm/projects/pyterrier/ColBERT/colbert/indexing/faiss_index_gpu.py", line 137, in _flush_to_cpu
    assert index.ntotal == offset+nb, (index.ntotal, offset+nb, offset, nb)
AssertionError: (33619968, 86536593, 0, 86536593)
```

Can you explain the purpose of the assertion? `index.ntotal` will not be the number processed if we are only doing one part of the index? 
Do I need to set slices to match the number of .pt files written by index.py (24)?

There is lots of terminology in the indexing code that isnt detailed in the paper.

**Comment by okhat** [comment]
That's correct: the assertion was being triggered on every call of _flush_to_cpu; it should be after the last _flush_to_cpu only. (This issue doesn't show when _flush_to_cpu is getting called only once.)

Just pushed a relaxation of the assertion. It should work now.

**Comment by okhat** [comment]
For FAISS indexing, here's a sample command for MS MARCO:

```python -m colbert.index_faiss --index_root /root/to/indexes/ --index_name IndexName --root /root/to/experiments --experiment ExperimentName --run OptionalRunName --partitions 65536 --sample 0.3```

You can probably remove `--sample 0.3` which will use a default (0.05). This will be faster and probably lose no effectiveness.

If this run cannot use faiss-gpu for any reason, you can also reduce `--partitions` to just 16384. This will be fast to index on CPU. It will make retrieval slightly slower, so it's a tradeoff.

The original runs in the paper used just 2000 partitions. Using up to 200k can yield much faster retrieval (much faster than the paper's results too) but you pay the cost upfront during faiss indexing.

If you use a large number of partitions, I recommends `--nprobe 16` or `--nprobe 32` during retrieval. Otherwise, `--nprobe 10` is more than enough for small partition numbers.

**Comment by cmacdonald** [comment]
Thanks Omar. Looking forward to seeing you tomorrow!

**Comment by okhat** [comment]
Looking forward to seeing you tomorrow as well!

**Comment by okhat** [comment]
Seems resolved. Closing but feel free to re-open if needed.
