### ISSUE TITLE
Indexing does not progress 

### ISSUE THREAD

**Issue by k-kharoub** [stanford-futuredata/ColBERT#130]
Every time I start indexing my collection , the status never change from "starting " even after hours. I am even testing with extremely small collection.
![image](https://user-images.githubusercontent.com/54174765/189458362-faea0501-5647-425b-ac2b-b63190423016.png)

**Comment by okhat** [comment]
Do you have a GPU? Is it being utilized while your code is running?

**Comment by Saiyam26** [comment]
@okhat I am facing the same issue. The GPU is being utilized while running the code (checked using torch.cuda.is_available())

**Comment by abdoelsayed2016** [comment]
![image](https://github.com/user-attachments/assets/764643a2-a79d-448b-9377-8b51f41f1134)


i have same issue 

>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.get_device_name(0)
'NVIDIA A30'
>>> torch.cuda.current_device()
0
>>>
