### ISSUE TITLE
How to use Colbert for Multilingual evaluation 

### ISSUE THREAD

**Issue by k-kharoub** [stanford-futuredata/ColBERT#131]
I am keen to evaluate ColBert in a multilingual setting. What do I need to change in model to use "[bert-base-multilingual-uncased]" during indexing , query encoding and retrieval ?
Is it sufficient to replace 'bert-base-uncased' with "[bert-base-multilingual-uncased]"  in hf_colbert.py

I am doing my master capstone project at University of Queensland on Multilingual dense retrievers.

**Comment by okhat** [comment]
Sorry for the delay on this. Is this still relevant?
