### ISSUE TITLE
Triplets creation

### ISSUE THREAD

**Issue by DonaldSailor** [stanford-futuredata/ColBERT#133]
Could you provide an information, how to create triplets?

**Comment by orionw** [comment]
The authors can reply with the exact answer, but AFAIK it's this: https://microsoft.github.io/msmarco/

**Comment by okhat** [comment]
@DonaldSailor Triples in what context? It depends on the dataset/task.

You can check out utility/supervision/triples.py for a script to do that.

That said, the overwhelming majority of the applications we're aware of do not need fine-tuning. Simply use the ColBERTv2 checkpoints; it'll be stronger than anything you can train in a small-medium amount of time.
