### ISSUE TITLE
fine-tuning ColBERT worsens retrieval quality

### ISSUE THREAD

**Issue by langineer** [stanford-futuredata/ColBERT#135]
I am fine-tuning Colbert on Natural Questions dataset following:
https://github.com/stanford-futuredata/ColBERT#training
Running evaluation after fine-tuning shows that it worsens ColBERT retrieval quality. 
Any pointers?

**Comment by okhat** [comment]
Discussed over email. tldr; it's hard to beat colbertv2 training with simple fine-tuning on triples, especially when sampling only one negative per <query, positive> pair. Closing.

**Comment by sudeepag** [comment]
Hi @okhat, apologies for pulling up such an old thread. It would be very helpful if you could share some more intuition from your email discussion. I am seeing the same result with my fine-tuning dataset, and am curious to learn more about why it is hard to beat zero shot performance with fine-tuning.
