### ISSUE TITLE
AssertionError in colbert/indexing/collection_indexer.py

### ISSUE THREAD

**Issue by Raincleared-Song** [stanford-futuredata/ColBERT#138]
Hello! When I tried to index my own corpus, I met with an AssertionError, shown in the following picture. Do you have any idea about what can cause such a problem? I also attach part of my code for indexing.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/51194713/198846605-92adbfc2-ea38-4976-8ebb-c28d606d8674.png">

```python
with Run().context(RunConfig(
        nranks=1,
        experiment="BioRADR",
        gpus=1,
        amp=False,
        overwrite=True,
)):
    config = ColBERTConfig(
        nbits=2,
        bsize=8,
        query_maxlen=64,
        doc_maxlen=512,
    )
    indexer = Indexer(checkpoint="colbertv2.0", config=config)
    indexer.config.save(f'bioradr/configs/{group_id}_config.json', overwrite=True)
    indexer.index(name=f"BioRADR-group-{group_id}",
                  collection=f'bioradr/tsv/{group_id}_collection.tsv', overwrite=True)
```

**Comment by Raincleared-Song** [comment]
I have tried some different corpus and I find that this problem will only appear for a few specific document sets. So I guess this issue may be concerned with some features of the data. But I hope to obtain your advice on how to fix this problem, thank you!

**Comment by Raincleared-Song** [comment]
I have tried some different corpus and I find that this problem will only appear for a few specific document sets. So I guess this issue may be concerned with some features of the data. But I hope to obtain your advice on how to fix this problem, thank you!

**Comment by bagchisu** [comment]
I get the same `AssertionError` when indexing my corpus. Any suggestions on why this could happen  is most welcome. Thanks.

**Comment by bagchisu** [comment]
Thanks. Yes, I can confirm that I had too many documents with almost the same contents. I can index well once I removed that.

**Comment by okhat** [comment]
We pushed a fix to this iirc. Let me know if you still face it. Closing otherwise.

**Comment by Raincleared-Song** [comment]
Acknowledged. Thanks.
