### ISSUE TITLE
on memory usage and FaissIndex.emb2pid

### ISSUE THREAD

**Issue by cmacdonald** [stanford-futuredata/ColBERT#14]
On the MSMARCO passage ranking task, this tensor is 687M entries - i.e. 2.4GB?

A multiprocessing Pool is then created for 16 processors - thus copying that tensor 16 times, consuming about 41GB of RAM.

The workaround is to make the tensor shared, but calling `share_memory_()` - see https://pytorch.org/docs/stable/tensors.html#torch.Tensor.share_memory_:
```
        print_message("len(self.emb2pid) =", len(self.emb2pid))
        # prevent this being copied to each fork
        self.emb2pid.share_memory_()
        self.parallel_pool = Pool(16)
````

Despite this, I still have memory problems on our environment - the forking consumes just too much memory, and the job is killed. Probably the faiss index is copied 16 times as well, and `all_doclens` also (though the latter is not needed at that point).

**Comment by okhat** [comment]
I see. I think the pool is only used in very specific cases (large batch processing tasks).

It seems like the easiest way to fix it is to avoid creating the pool by default. It only affects line 112.

**Comment by cmacdonald** [comment]
Indeed. I have removed it from my local copy.
________________________________

**Comment by okhat** [comment]
Thank your for this note! I will have it behind a flag.

**Comment by cmacdonald** [comment]
I would still recommend `self.emb2pid.share_memory_()` - its a no-op if its in CUDA.
