### ISSUE TITLE
Decompression returns zero vectors

### ISSUE THREAD

**Issue by danielfleischer** [stanford-futuredata/ColBERT#141]
Hi, when reconstructing vectors from codes and residuals I always get zero vectors. The relevant code is related to the torch extensions. See minimal example:

```python
from colbert.indexing.codecs.residual import ResidualCodec, ResidualEmbeddings

codec = ResidualCodec.load("/path/to/index/")

a = ResidualEmbeddings(torch.Tensor([1,2,3]),
                       torch.randint(256, (3, 32),
                                     dtype=torch.uint8))

codec.decompress_residuals(a.residuals,
                           codec.bucket_weights,
                           codec.reversed_bit_map,
                           codec.decompression_lookup_table,
                           a.codes,
                           codec.centroids,
                           codec.dim,
                           codec.nbits)
```

this returns zero vectors. The index has content (examine the `pt` files). 

Did anyone encounter this? is this a bug or an issue with GPU drivers?

Thanks!

**Comment by danielfleischer** [comment]
Indexing works. Searching works but it's subtle; candidates are collected using the heuristic of using the centroids as proxies. Next, we want to reconstruct the full vectors for ranking + topK. Here I get zero vectors (see issue); the vectors become NaN after normalization, ranking doesn't do anything and I get topK documents which look relevant (heuristics work) but the scores are NaN, which started the debugging and led to me to pin point the issue.

**Comment by okhat** [comment]
Are you doing this to debug the standard Searcher, or are you trying to re-implement your own search? That wasn't clear to me.

**Comment by danielfleischer** [comment]
I want to use the library and am debugging the current code. I got Nan scores when searching and from there I saw the decompression returns zero vectors.

**Comment by okhat** [comment]
Thanks. I've never seen that before. Are you using the checkpoint we provide? What information can you provide about your collection: how many passages, passage language, lengths, etc.

**Comment by okhat** [comment]
Information about the hardware will also be helpful.

**Comment by okhat** [comment]
Also. Did you try the provided example in the Jupyter notebook? Does that work and give you non-NaN scores?

**Comment by danielfleischer** [comment]
Hi, we were able to successfully create a `searcher` object (like in the demo jupyter code) that returns non-Nan scores on RTX 3090. 

Could there be some Cuda dependencies that can only run on newer cards?

**Comment by okhat** [comment]
We were able to get normal behavior on Titan X. I have to assume your specific cuda setup on Titan X is different in some important way.

**Comment by danielfleischer** [comment]
Ok, thanks!
