### ISSUE TITLE
How do I access colbert.index and colbert.index_faiss ? 

### ISSUE THREAD

**Issue by lboesen** [stanford-futuredata/ColBERT#144]
Hi :) 

I am trying to index using below code:

```
python -m torch.distributed.launch --nproc_per_node=4 -m 
colbert.index --amp --doc_maxlen 180 --mask-punctuation --bsize 256 
--checkpoint /colBERT/ 
--collection /data/collection.tsv \
--index_root /model_runs/ \
--index_name INDEX.COLBERT\
--root /model_runs/experiments/ \
--experiment MSMARCO-psg

python -m colbert.index_faiss 
--index_root /model_runs/ 
--index_name INDEX.COLBERT
--root /model_runs/experiments/ 
--experiment MSMARCO-psg
```

But I am getting following errors:
/home/anaconda3/envs/myenv/bin/python: Error while finding module specification for 'colbert.index_faiss' (ModuleNotFoundError: No module named 'colbert')
/home/anaconda3/envs/myenv/bin/python: Error while finding module specification for 'colbert.retrieve' (ModuleNotFoundError: No module named 'colbert')

I am thinking its because I need from the branch: https://github.com/stanford-futuredata/ColBERT/tree/colbertv1
But how do I clone this branch ?

**Comment by okhat** [comment]
Yes, you need the v1 branch. Follow the instructions there for installation and use. For git cloning it, see https://stackoverflow.com/questions/1911109/how-do-i-clone-a-specific-git-branch
