### ISSUE TITLE
intro.ipynb notebook not running first cell on CPU environment: missing modules

### ISSUE THREAD

**Issue by jramirezpr** [stanford-futuredata/ColBERT#146]
If you try to run the first cell, you get as the end of the trace the error:
modulenotfounderror: No module named 'git'
I fixed it with

```
pip install GitPython
```
then you get an error about missing transformers so ran this
```
 pip install transformers[torch]
```
then it runs fine. 
these two packages should be added to the CPU environment yaml file, or added to the README.md as part of the install instructions.

**Comment by okhat** [comment]
Please don't install with pip. Follow the conda instructions in the README. Does that fix the issue?

**Comment by jramirezpr** [comment]
I did not install ColBERT with pip, I created the environment using the CPU .yml with conda. The pip is for resolving the issues about the two missing packages.

________________________________
De: Omar Khattab ***@***.***>
Enviado: lunes, 12 de diciembre de 2022 12:37 p. m.
Para: stanford-futuredata/ColBERT ***@***.***>
CC: Juan Carlos Ramirez ***@***.***>; Author ***@***.***>
Asunto: Re: [stanford-futuredata/ColBERT] intro.ipynb notebook not running first cell on CPU environment: missing modules (Issue #146)


Please don't install with pip. Follow the conda instructions in the README. Does that fix the issue?

**Comment by okhat** [comment]
Hmm are you sure the conda env you created is being used in jupyter then? This error seems like it's not aware of the conda stuff.

**Comment by jramirezpr** [comment]
I think that solved it. I just deleted it and recreated it, then ran conda install -c anaconda jupyter,  and now it is working. It is most likely that I was using another environment's jupyter  like you mentioned (makes sense, since the environment created with the .yml didn't have jupyter as dependency, usually I install jupyter on Anaconda UI homepage but cannot recall doing so)

________________________________
De: Omar Khattab ***@***.***>
Enviado: martes, 10 de enero de 2023 11:26 a. m.
Para: stanford-futuredata/ColBERT ***@***.***>
CC: Juan Carlos Ramirez ***@***.***>; Author ***@***.***>
Asunto: Re: [stanford-futuredata/ColBERT] intro.ipynb notebook not running first cell on CPU environment: missing modules (Issue #146)


Hmm are you sure the conda env you created is being used in jupyter then? This error seems like it's not aware of the conda stuff.

**Comment by okhat** [comment]
Awesome! Feel free to close or re-open as needed
