### ISSUE TITLE
Possible to train from checkpointed model with new triples?

### ISSUE THREAD

**Issue by bagchisu** [stanford-futuredata/ColBERT#150]
I have successfully trained a new model from scratch using triples generated from the ground truth of queries and relevant docs in my collection. However, when trying to train with these triples starting from the provided ColBERTv2 checkpoint, I run into an assertion error:

```
AssertionError: Q.size(0)=1024, D_padded.size(0)=32
Traceback (most recent call last):
  <skipped previous calls>
  File "<repo_base>/ColBERT/colbert/modeling/colbert.py", line 173, in colbert_score
    assert Q.size(0) in [1, D_padded.size(0)], f"Q.size(0)={Q.size(0)}, D_padded.size(0)={D_padded.size(0)}"
AssertionError: Q.size(0)=1024, D_padded.size(0)=32
``` 
(I added the assertion message.)

I tried to do this by following the code snippet in the [training section](https://github.com/stanford-futuredata/ColBERT#training) of the README, but making the following change:

```python
checkpoint_path = trainer.train(checkpoint=initial_checkpoint_path) 
```
where `initial_checkpoint_path` points to the dir containing the downloaded checkpoint.

Is this the correct way? Thanks.

**Comment by okhat** [comment]
Hmm, can you set the config to include the defaults explicitly.

```ColBERTConfig(bsize=32, lr=3e-06, warmup=None, doc_maxlen=180, dim=128, nway=2, accumsteps=1, use_ib_negatives=False)```

I suspect the defaults are being overriden from the checkpoint you're trying to use.

**Comment by bagchisu** [comment]
Thanks, specifying the defaults allowed the training to complete.
