### ISSUE TITLE
Where is the codebase for demostrate-search-predict paper?

### ISSUE THREAD

**Issue by Maxlinn** [stanford-futuredata/ColBERT#154]
hi to all the team, recently i'm interested in your work [DEMONSTRATE–SEARCH–PREDICT: Composing retrieval and language models for knowledge-intensive NLP](https://arxiv.org/abs/2212.14024)

the paper says the codebase is in this repo, but i can't find any.

Has it been released yet? or did i miss something? thanks in advance for your kind help.

**Comment by okhat** [comment]
Thanks for your interest! The paper says "We _will_ release DSP as open source at [url]."

We will! Working on it.

**Comment by Maxlinn** [comment]
thanks for reply in time, i'm really looking forward to it!

**Comment by abhinavkulkarni** [comment]
@Maxlinn: It has been released here: https://github.com/stanfordnlp/dsp
