### ISSUE TITLE
Turning off compression and centriod

### ISSUE THREAD

**Issue by eugene-yang** [stanford-futuredata/ColBERT#155]
I'm wondering if there is an easy way to turn off the compression and centroid for indexing and searching -- essentially going back to v1. 
Thanks!

**Comment by santhnm2** [comment]
The v1 version of the code is available on the `colbertv1` branch (https://github.com/stanford-futuredata/ColBERT/tree/colbertv1) if that works for your use case

**Comment by okhat** [comment]
That — or use nbits=4 or nbits=8 for far less aggressive compression

**Comment by eugene-yang** [comment]
Since I have modified the codebase quite a bit, it would be nice if I could play with the case where compression is not in place without going back to modify the v1 codebase again.

I believe `nbits=16` would be no compression if we train with half precision, right? But based on what I can tell, it's not straightforward to use `nbits=16`, right?

**Comment by okhat** [comment]
Definitely don’t advise =16 with this code. There are reasons it won’t be the same as no compression. 4 or 8 should do

**Comment by eugene-yang** [comment]
Alright. Thanks @okhat!

**Comment by CosimoRulli** [comment]
Hello @okhat, it is possible to employ the ```colbertv1``` branch with ```colbertv2``` checkpoint? I am interested in obtaining the uncompressed representations of the vectors in the MS MARCO dataset generated using colbertv2 due to its higher effectiveness.

**Comment by okhat** [comment]
@CosimoRulli You can use the Checkpoint class to encode passages or queries without indexing or compressing them!
