### ISSUE TITLE
using collection

### ISSUE THREAD

**Issue by bryanhpchiang** [stanford-futuredata/ColBERT#161]
some questions

1. can i pass in path=None and data as a list of strings (passages) when initializing a Collection?
2. let's say i want to create multiple indexes that i might want to switch between often 

should i use the same run config for all of them to get better performance (i only need to load one run) ? as in is this supported

3. is there some way to restrict the indexer to a specific GPU on the machine?

**Comment by bryanhpchiang** [comment]
did some testing
1. yes, tested
2. yes, tested
3. not super sure yet might need some combination of CUDA_VISIBLE_DEVICES and setting nranks

**Comment by okhat** [comment]
Your answer for 3 is correct. I think you can also do gpus=[1] and it'll work

**Comment by bryanhpchiang** [comment]
tenks
