### ISSUE TITLE
RuntimeError: Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at /project/faiss/faiss/Clustering.cpp:283: Error: 'nx >= k' failed: Number of training points (71) should be at least as large as number of clusters (128)

### ISSUE THREAD

**Issue by bryanhpchiang** [stanford-futuredata/ColBERT#162]
i made my own small collection, and i'm running into this error

RuntimeError: Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at /project/faiss/faiss/Clustering.cpp:283: Error: 'nx >= k' failed: Number of training points (71) should be at least as large as number of clusters (128)

what's the fix? is there a minimum collection size that i should be using? or should each passage in the collection be at least a certain length? thanks!

**Comment by bryanhpchiang** [comment]
ok i just think passages need to be of a certain length.

**Comment by okhat** [comment]
No, length is not a problem. But it seems like your collection is extremely small in terms of # of total tokens.

I'd index no less than a few hundred passages.

**Comment by bryanhpchiang** [comment]
hmmmmmmmm ok thanks
