### ISSUE TITLE
torch.cat consume large amount of memory

### ISSUE THREAD

**Issue by dayuyang1999** [stanford-futuredata/ColBERT#171]
Dear author,

I saw that in `/home/dayu/convir/ColBERTv1/colbert/indexing/faiss.py", line 35 , this step

```
sample = torch.cat(sample).float().numpy()
```
will consume large amount of memory, which my machine cannot handle. Is there any alternative solution for this?

Best,
Dayu

**Comment by sarisel** [comment]
Lower precision such as `float16` might help
