### ISSUE TITLE
how multi-slice FAISS indeces can be used for retrieval

### ISSUE THREAD

**Issue by dayuyang1999** [stanford-futuredata/ColBERT#172]
Dear authors,

It seems all examples pre-assume the faiss index has `slice=1`. Can you provide more clue about what is the change should I made when `slice=N` when retrieval? 

I have passed the correct `offset` and `endpos` when creating the path of the index, using `get_faiss_index_name`.
But, I am not sure how to retrieve, I am confused with the `part_range` argument used in creating the `FaissIndex` object.

Thanks!
Dayu

**Comment by okhat** [comment]
I don’t know if we still have support for these features in v1. I suggest you use v2 indexing or at least manually index N different slices from scratch and merge the search results.
