### ISSUE TITLE
Add logic to setup and query a remote ColBERT server

### ISSUE THREAD

**Issue by abhinavkulkarni** [stanford-futuredata/ColBERT#173]
Hi,

I was going through the [DSP intro notebook](https://colab.research.google.com/github/stanfordnlp/dsp/blob/main/intro.ipynb)  and observed that it uses a remote ColBERTv2.0 server. Can you please add the same functionality in the main branch and update the documentation?

Most of us do not have access to heavy GPUs and rely on cloud providers for the same. Currently, the only way to setup and query a ColBERTv2.0 index is to do so locally.

Thanks!

**Comment by okhat** [comment]
Thanks! @VThejas is working on this..

**Comment by okhat** [comment]
Btw, the ec2 server running colbert only has CPUs! But you need gpus for indexing

**Comment by okhat** [comment]
Now here: https://github.com/stanford-futuredata/ColBERT#running-a-lightweight-colbertv2-server

**Comment by okhat** [comment]
See the overview (or intro notebook for ColBERT) for how to do indexing
