### ISSUE TITLE
 Index error

### ISSUE THREAD

**Issue by HuMian10** [stanford-futuredata/ColBERT#176]
Hi
  During my training process, the model has been iterated 5000 times, and the output batch_idx=5000, but the model training still has not stopped. I manually terminated the process, and then when running indexer.py for indexing, The saved 4000 iterations of the model parameters should be used, but during the run, An error occurred in the indexer.py 

assert (overwrite in [True, 'reuse', 'resume']) or index_does_not_exist, self.config.index_path_.

  So I would like to ask you if this problem is caused by me not training the model, or if there is another reason. Thank you for taking the time to guide me

**Comment by okhat** [comment]
Manually stopping training is totally fine. The indexing error is not related to training

**Comment by okhat** [comment]
The assertion error you're seeing seems to indicate you're calling the indexer with an incorrect value for the "overwrite" key. It can only be set to True or 'reuse' or 'resume'.

**Comment by HuMian10** [comment]
> The assertion error you're seeing seems to indicate you're calling the indexer with an incorrect value for the "overwrite" key. It can only be set to True or 'reuse' or 'resume'.

I output overwrite at the moment before the assertion, which is False
 
![image](https://user-images.githubusercontent.com/101257078/220856225-576c1576-8758-49e9-90e5-0ab508978a12.png)

**Comment by okhat** [comment]
Hmm interesting. Can you set it to True

**Comment by okhat** [comment]
It can’t be false

**Comment by HuMian10** [comment]
> Hmm interesting. Can you set it to True
Manually set to True, will not affect the program running？

**Comment by okhat** [comment]
Yup set it to True and run again

**Comment by HuMian10** [comment]
> Yup set it to True and run again

Thanks. Now the program is working properly
