### ISSUE TITLE
on [PAD] as an actual token

### ISSUE THREAD

**Issue by cmacdonald** [stanford-futuredata/ColBERT#18]
A real MSMARCO document:
```
427711	Peripheral Vascular Disease (PVD; Peripheral Artery Disease [PAD]). Peripheral vascular disease (PVD) is a problem with poor blood flow. It affects blood vessels outside of the heart and brain and gets worse over time.Parts of the body, like the brain, heart, arms, or legs, may not get enough blood.The legs and feet are most commonly affected.eripheral vascular disease (PVD) is a problem with poor blood flow. It affects blood vessels outside of the heart and brain and gets worse over time. Parts of the body, like the brain, heart, arms, or legs, may not get enough blood. The legs and feet are most commonly affected.
```

Note that `[PAD]` here is an actual token. BERT Tokeniser assigns it the actual PAD token id, i.e. 0. Later, colbert.mask() removes it (as it is token id 0). Note that normal padding tokens are removed by the attention mask passed to the self.bert(). There are 11 such documents with `[PAD]` as a token MSMARCO passage corpus.

So is colbert.mask() correct, or should the BertTokenizer have tokenised it normally?

**Comment by okhat** [comment]
That's interesting and, in hindsight, is to be expected with other special tokens in any large collection (e.g., there's probably [SEP] too).

I guess the right thing is to tokenize them into three tokens including the square brackets?

But I don't think this has any significant impact, unless someone is searching for special tokens?

**Comment by cmacdonald** [comment]
I've been adapting code looking at alignments, and this tripped me up. I wondered if the `x!=0` is really needed in `colbert.mask()`, as special tokens are removed using the normal attention masking?

**Comment by okhat** [comment]
Surprisingly, it actually matters. The attention mask doesn't prevent non-zero outputs. It just makes sure other tokens don't attend to the masked positions.

**Comment by okhat** [comment]
The other thing is that the masks remove pad tokens before saving documents to disk in indexing. This probably saves some space.

**Comment by cmacdonald** [comment]
Interesting. I was surprised that the BERT tokeniser would accept [PAD] as a token - I though special tokens had to be appended to the generated ids; I guess the impact is for queries involving something abbreviated as PAD, SEP etc.  

Sure, trailing PADs need to continue to be removed. Anyway, its an observation rather than a bug.

**Comment by okhat** [comment]
I agree it's worth addressing, especially in a production system. The easiest way is to surround all square brackets with spaces in the original text (i.e., via an all replace).

**Comment by okhat** [comment]
Hi Craig! I just saw this ECIR'21 preprint that seems to do some analysis about alignment.  https://arxiv.org/abs/2012.09650

Not much about [MASK]s though.
