### ISSUE TITLE
Support for other languages (Spanish, German, etc..)

### ISSUE THREAD

**Issue by dbuos** [stanford-futuredata/ColBERT#185]
Hi there!

Is there any version of the pre-trained weights the was trained with data other than english? for example using https://arxiv.org/abs/2108.13897 mMARCO: A Multilingual Version of the MS MARCO ?

**Comment by okhat** [comment]
We haven't trained a version like this ourselves, but check out PrimeQA! They have multi-lingual colbert models iirc.
