### ISSUE TITLE
Reranking/Validation with ColBERT v2?

### ISSUE THREAD

**Issue by orionw** [stanford-futuredata/ColBERT#191]
I was wondering if it's possible to do validation/reranking with ColBERT v2 in the same way as v1 (e.g. https://github.com/stanford-futuredata/ColBERT/tree/colbertv1#validation). I don't see an option for it in the main repo code (possibly because it is not compatible with the compression and other techniques) but I may be missing something.

If there is no implementation for it and I'm okay with missing out on the quantization and other compression methods, can I simply use the v1 code for validation with the v2 weights?

**Comment by okhat** [comment]
V2 weights are unlikely to work in v1 code without some changes.

What's the need for reranking though? Indexing is now faster and has a smaller footprint.

Anyway, if you have a set that needs reranking (e.g., smaller number of documents; too small to index, or very frequently changing content), you can use the Checkpoint class in v2. This class can do docs_from_text and queries_from_text and gives you embeddings that it can score on the fly.

**Comment by plamb-viso** [comment]
@okhat can the Checkpoint class be used with `HF_ColBERT` as a super class  https://huggingface.co/colbert-ir/colbertv2.0/tree/main can be used as the pretrained model?
