### ISSUE TITLE
Scores Setting

### ISSUE THREAD

**Issue by HuMian10** [stanford-futuredata/ColBERT#193]
How is the socres set for the output, is there a fixed mapping interval, because I see that it often outputs in the twenties, how do I set the component number range from 0 to 1

**Comment by okhat** [comment]
You can divide the scores by query_max_len (i.e., 32) to get scores between 0 and 1

**Comment by okhat** [comment]
Or, if you have more than one score, you can turn them into a probability distribution (sum to one) by a softmax layer
