### ISSUE TITLE
colbert evaluation 

### ISSUE THREAD

**Issue by zhangzhen-research** [stanford-futuredata/ColBERT#198]
in colbert-v1, I want to know if only the evaluation of re-rank task is included in the code base, not for ranking from the full collection,
because in the validation part, top-k file is always needed

**Comment by zhangzhen-research** [comment]
hello？

**Comment by okhat** [comment]
I don't understand the question unfortunately. Is this about colbertv1? If so, what about the reranking script is unclear?
