### ISSUE TITLE
is v0.2 available now?

### ISSUE THREAD

**Issue by DreamsofGg** [stanford-futuredata/ColBERT#20]
@okhat Hi! Thanks for your paper and repo! It seems that everything of v2 is ready, I just wanna make sure whether it is totally available in terms of performence of the model trained by version 2, i.e. command
```
python -m colbert.train --triples triples.train.small.tsv
```
thx! : )

**Comment by okhat** [comment]
Hi @DreamsofGg !

You can use this:

```
CUDA_VISIBLE_DEVICES="0,1,2,3" python -m torch.distributed.launch --nproc_per_node=4 -m colbert.train --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 --triples /path/to/triples.tsv --similarity l2   --root /root/to/log/experiments/data/   --experiment ExperimentName
```

You can modify the number of GPUs (e.g., `CUDA_VISIBLE_DEVICES="0"` and `--nproc_per_node=1`) as needed.

Let me know if you face any issues!

**Comment by DreamsofGg** [comment]
Wow! your command just need half time to finish training! (Also with a single gpu)  Great thanks!

**Comment by DreamsofGg** [comment]
@okhat sorry to bother again. I found that the similarity  used in the paper is cosine_sim, so how l2_sim influence the results?

**Comment by okhat** [comment]
Actually both are mentioned in the paper, see Table 1 vs. Table 2.

There shouldn't be a major difference in performance; feel free to use either one.
