### ISSUE TITLE
Best way to compute ColBERT score for a query-document pair?

### ISSUE THREAD

**Issue by rohitpatki** [stanford-futuredata/ColBERT#203]
I have a trained ColBERT model from custom data. I don't want to retrieve top-K for a query but just want to get the CoLBERT score for a query-document pair. Whats the best way to do that?

**Comment by okhat** [comment]
See the Checkpoint class!

**Comment by rohitpatki** [comment]
Thank you!

**Comment by franziskaweber** [comment]
Hello @rohitpatki, hello @okhat,

I would also like to compute the CoLBERT score for query-document pairs. I am still struggeling to encode my query and document in a way that I can use the score-function of the checkpoint class.
Any explanation on how do to the encoding would be appreciated!
