### ISSUE TITLE
installing neuralIR and colbert packages

### ISSUE THREAD

**Issue by prushto** [stanford-futuredata/ColBERT#208]
Hi, please could you clarify the steps required here? `pip install neuralIR` seems to work, but the `colbert` package is not recognized. Thanks!

**Comment by prushto** [comment]
Hi!

neuralIR appears to be related to Colbert?
https://pypi.org/project/neuralIR/

The conda installation steps in your readme don't seem to address how colbert is installed, but perhaps I am missing something. I ended up using git clone instead.

Thanks!

**Comment by okhat** [comment]
I’m not familar with that pip project. It seems based on old colbert versions. 

Please follow the conda instructions. They install all of colbert’s dependencies. See the intro notebook for how to run colbert after these conda steps

**Comment by prushto** [comment]
When I followed the conda instructions in the readme and ran the intro notebook, this was my experience:

`from colbert.infra import Run, RunConfig, ColBERTConfig
from colbert.data import Queries, Collection
from colbert import Indexer, Searcher

...

ModuleNotFoundError: No module named 'colbert.infra'`

As mentioned, I used git clone instead to solve this.

Hope this is helpful feedback!

**Comment by prushto** [comment]
Yes it worked, thank you, I'm all set!

**Comment by okhat** [comment]
Glad to hear that! Please feel free to open new issues if you need other help
