### ISSUE TITLE
nranks for no GPUs

### ISSUE THREAD

**Issue by prushto** [stanford-futuredata/ColBERT#209]
I am running the cell below in the intro.ipynb notebook. 

Sorry if this is covered elsewhere, but what should nranks equal if I want to run this on CPUs only?

Also is there an option to see progress on this step? I understand it could take hours to execute on CPUs so I want to ensure it's not stuck.

```
with Run().context(RunConfig(nranks=4, experiment='notebook')):  # nranks specifies the number of GPUs to use.
    config = ColBERTConfig(doc_maxlen=doc_maxlen, nbits=nbits)

    indexer = Indexer(checkpoint=checkpoint, config=config)
    indexer.index(name=index_name, collection=collection, overwrite=True)
```

Thank you!

**Comment by okhat** [comment]
We don't currently support indexing with no GPUs unfortunately. But you can use a free GPU on Colab

**Comment by prushto** [comment]
Got it, thank you!
