### ISSUE TITLE
Cannot access pretrained model

### ISSUE THREAD

**Issue by AshwinRamachandran2002** [stanford-futuredata/ColBERT#217]
Hi,
I cannot access the COLBERTv2 pretrained model here:  https://downloads.cs.stanford.edu/nlp/data/colbert/colbertv2/colbertv2.0.tar.gz

**Comment by okhat** [comment]
Ah yes! The server is down for a week. Let me figure out uploading it elsewhere for you

**Comment by AshwinRamachandran2002** [comment]
Yes, thank you

**Comment by henry-merrilees** [comment]
likewise, thanks!

**Comment by okhat** [comment]
https://huggingface.co/colbert-ir/colbertv2.0

You can probably (NOT tested!) just pass "colbert-ir/colbertv2.0" in the checkpoint parameter of the Indexer!

**Comment by AshwinRamachandran2002** [comment]
Thank you very much!

**Comment by jon-chuang** [comment]
Perhaps it's better to just use the huggingface link in the README permanently? :)
