### ISSUE TITLE
How to embed and score a query-document-pair?

### ISSUE THREAD

**Issue by franziskaweber** [stanford-futuredata/ColBERT#222]
I would like to use ColBERT to compute the embeddings of a query and of a document and to score the (query, document)-pair.

1. I want to use the pre-trained ColBERTv2 checkpoint. Is it correct to compute the query- and document-embeddings in the following way?
```python
nbits = 2
doc_maxlen = 300
config = ColBERTConfig(doc_maxlen=doc_maxlen, nbits=nbits, kmeans_niters=4)
checkpoint = Checkpoint('path_to_colbertv2.0', colbert_config=config)
Q = checkpoint.queryFromText([query])
D = checkpoint.docFromText([document])
```

2. [Here](https://github.com/stanford-futuredata/ColBERT/issues/203#issuecomment-1552293967) it is stated that one should use the `checkpoint` class to compute the score of a (query, document)-pair. However, the `score`-function in the `checkpoint` class states that one should use `colbert_score`. I tried using `colbert_score` but I don't know how to obtain the expected `D_padded` and `D_mask` arguments.

Any help on how to proceed would be highly appreciated!

**Comment by franziskaweber** [comment]
What shape should `D_mask` have?

I tried `D_mask=torch.ones(D.size())` but this leads to the Runtime Error `shape '[1, 26]' is invalid for input of size 3328`.

**Comment by okhat** [comment]
The first 2 dima of D iirc

**Comment by franziskaweber** [comment]
Thank you, that worked!
