### ISSUE TITLE
Clarification about the tokenization process

### ISSUE THREAD

**Issue by marcospiau** [stanford-futuredata/ColBERT#231]
Hi,
I am making some changes to the code to make it possible to use with non-BERT models.
Besides "registering" the correct checkpoint paths and model classes on `hf_colbert.py` (which is easy) the main challenge is to adapt the tokenization part, because the tokenizer is different (e.g., no [MASK] and [CLS] tokens). Can you guys help with some questions?.
*  in `query_tokenizer.py`, what exactly is `context` on the `tensorize` method? I tried to follow the code but could't figure it out 
* are the `tokenize` and `encode` methods used anywhere? They are defined on both `query_tokenization.py` and `doc_tokenization.py` files, but I couldn't find any reference to them in the code. My guess is they were used on previous versions.
* `mask_punctuation=True` is the default, so there is no attention to punctuation tokens. Have you observed how the effectiveness is impacted if `mask_punctuation=False` is used?

Thanks in advance!

**Comment by okhat** [comment]
Non BERT encoders are already supported. No?

**Comment by marcospiau** [comment]
I am trying to use T5 models (the encoder part). I was able to load the models correctly by modifying `hf_colbert.py` accordingly, but the current tokenization logic doesn't work correctly because of the different control tokens ([CLS], etc).

**Comment by okhat** [comment]
You can ignore the context argument; it’s only for Baleen not ColBERT.

Tokenize and encode may be used in the training batchers.

MaskIng punctuation is optional. It’s to save space.

**Comment by marcospiau** [comment]
Thanks @okhat ! Really appreciate your quick response!
