### ISSUE TITLE
How to use pre-trained ColBERTv2 checkpoint?

### ISSUE THREAD

**Issue by AjinkyaBankar** [stanford-futuredata/ColBERT#232]
I am working on my computer. I have downloaded [pre-trained ColBERTv2 checkpoint](https://downloads.cs.stanford.edu/nlp/data/colbert/colbertv2/colbertv2.0.tar.gz). It's `.tar.gz` file. Do we have to uncompress this file and set the `pytorch_model.bin` as a `checkpoint file path` in the `Indexer(checkpoint=checkpoint file path, config=config)`? Or set the path of the entire uncompressed directory `colbertv2.0`? 

I have tried both ways, but doesn't complete the indexing process. It just shows the cell as busy and even doesn't throw any error.

**Comment by okhat** [comment]
This works: https://colab.research.google.com/github/stanford-futuredata/ColBERT/blob/main/docs/intro2new.ipynb

**Comment by AjinkyaBankar** [comment]
@okhat I want to implement this on a local machine (without internet connection). I can download the compressed checkpoint file in advance, and save at the appropriate location. In your notebook, where is the model saved for `checkpoint = 'colbert-ir/colbertv2.0'`?

**Comment by okhat** [comment]
Okay, then check out the notebook in this repo. It does have instructions for the extraction of the tar.gz

**Comment by AjinkyaBankar** [comment]
@okhat I did those steps. But it still isn't working. The following cell keeps executing forever without returning any error nor any message:
![image](https://github.com/stanford-futuredata/ColBERT/assets/77496039/bc39a1d7-18ac-4f2c-98e2-b7cb2247bbb7)
```
[Aug 7, 18:27:33] #> Creating directory /ajinkya/experiments/notebook/indexes/lifestyle.dev.2bits 

#> Starting...
```

1. Can we see detailed logs for the above step, such as `verbose=True`?
2. Another possibility is package incompatibility. I can't use Conda on my computer. Therefore, I have installed packages using pip commands. Can you provide a `requirements.txt` file for the required packages with their version numbers?

**Comment by AjinkyaBankar** [comment]
This is an interesting technique for text retrieval. But unable to implement due to lack of support outside conda environment. I would really appreciate if someone can help.

**Comment by AjinkyaBankar** [comment]
When I ran the code on local python IDE instead of notebook, I could detect the reason for my problem of forever execution. It said `RuntimeError: Ninja is required to load C++ extensions.` I had to debug a lot on fixing it by downgrading `torch`, installing `cuda` libraries, `nvcc` and `ninja-build`. Now it doesn't need `conda` environment.
