### ISSUE TITLE
Using ColBERTv2 for re-ranking

### ISSUE THREAD

**Issue by plamb-viso** [stanford-futuredata/ColBERT#235]
I'm interested in using ColBERTv2 for re-ranking already-ranked approximate nearest neighbor results.  I couldn't find any docs or examples that exactly match this use case. My thinking is that I would pass ColBERT a query string and either a batch of ranked ANN results or pass the query and each result 1 by 1.

If you're using it this way, however, you wouldn't `Index` the "document" data beforehand. For people using it this way, do you create an `Index` on the fly with your set of ranked ANN results and then pass the query/ANN results into it? If so, can an `Index` be created in just memory instead of going to disk?

Curious for the answers to these questions and in general best practices for re-ranking semantic search results with ColBERTv2

**Comment by plamb-viso** [comment]
Came across this other issue which anyone else reading this might find interesting: https://github.com/stanford-futuredata/ColBERT/issues/191

**Comment by okhat** [comment]
Some code I found.

```python
from colbert.modeling.checkpoint import Checkpoint
from colbert.infra import ColBERTConfig

import torch
ckpt = Checkpoint("colbertv2.0", colbert_config=ColBERTConfig(
            root="experiments",
        ))

Q = ckpt.queryFromText(["some query"], bsize=32)[0]
Q = Q.unsqueeze(0)
D = ckpt.docFromText(all_passages, bsize=32)[0]
print(len(D), len(Q))

from colbert.modeling.colbert import colbert_score

print(D.shape)

D_mask = torch.ones(D.shape[:2], dtype=int)
print(D_mask.shape)
print(colbert_score(Q, D, D_mask))
```

**Comment by okhat** [comment]
lmk if it works or needs some tweaks for what you'r trying to do

**Comment by plamb-viso** [comment]
This example worked. Two changes I had to make

- In  `class ColBERT` in the `__init__` method I had to add `colbert_config = self.colbert_config` so the `colbert_config` variable is set to the config that comes out of `BaseColBERT` by default 
- In `class Checkpoint` in the `__init__` method I added `self.colbert_config.checkpoint = name` because I am passing `"colbert-ir/colbertv2.0"` to `Checkpoint` so it loads everything from that v2 checkpoint

**Comment by plamb-viso** [comment]
@okhat i was able to get it producing scores and even able to export the query forward pass and doc forward pass via onnx.

One thing that is strange is in the number examples i've run, the `colbert_score` has never been higher than ~20.5. I assume it ranges from 0-100. It could be that my docs are that dissimilar, but it seems odd. Is this something to be concerned about?

**Comment by okhat** [comment]
It goes up to 32, or whatever query max len js

**Comment by plamb-viso** [comment]
For anyone who stumbles on this and is interested in onnx export, the Vespa folks provide a code example at the bottom of this: https://huggingface.co/vespa-engine/colbert-medium

Thanks for all the pointers @okhat
