### ISSUE TITLE
What is faiss actually used for?

### ISSUE THREAD

**Issue by lambdaofgod** [stanford-futuredata/ColBERT#237]
First of all, let me thank you for providing this code. I don't often see such research-related code of such quality.

I see that faiss is only used in [collection_indexer](https://github.com/stanford-futuredata/ColBERT/blob/4b1885f3b4eb9f0f6cca1bc890d89f3f849504b9/colbert/indexing/collection_indexer.py#L477).

Because of my experience of running into all kinds of nasty bugs with faiss I'd like to consider removing it from dependencies.

Is my understanding right that removing faiss would only require replacing `compute_faiss_kmeans`?

Of course if I get to it I'd leave faiss kmeans but I'll add alternative kmeans implementation that will be used when it's specified in config.

**Comment by santhnm2** [comment]
This is correct, FAISS is only used for the k-means computation.
