### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by hoangtrungnguyen1010** [stanford-futuredata/ColBERT#238]
This is error i have. I use conda to create the env with conda_env.yml.
![image](https://github.com/stanford-futuredata/ColBERT/assets/80197933/70b4e874-43fa-48b1-ac12-23004e14cfb0)
![image](https://github.com/stanford-futuredata/ColBERT/assets/80197933/b593c532-11d3-4395-b01a-34cb87c8b73c)

**Comment by sysu18363025** [comment]
Hello，I miss the same question. I wonder how you deal with it.

**Comment by IgorSondors** [comment]
@hoangtrungnguyen1010 Hello. Please share your solution of the bug!

**Comment by timbmg** [comment]
I am also facing this issue. Any solutions @hoangtrungnguyen1010, @sysu18363025, @IgorSondors?

**Comment by IgorSondors** [comment]
@timbmg make sure you have installed pytorch and faiss-gpu with gpu enabled

That helped me:
`pip install faiss-gpu`
