### ISSUE TITLE
Indexer throwing error : module 'torch.distributed' has no attribute 'is_initialized'

### ISSUE THREAD

**Issue by H4R5H1T-007** [stanford-futuredata/ColBERT#241]
I am trying to run colbert on macbook and it's throwing me this error while running indexer.
I solved it by replacing [line 146 of `collection_indexer.py`](https://github.com/stanford-futuredata/ColBERT/blob/4b1885f3b4eb9f0f6cca1bc890d89f3f849504b9/colbert/indexing/collection_indexer.py#L146C51-L146C51) with 
`if torch.distributed.is_available() and torch.distributed.is_initialized()` and it worked but I am not sure if it's the right method to solve the error.

**Comment by okhat** [comment]
Ah nice. I think this makes sense. Wanna open a PR? We’ll double check then merge it

**Comment by H4R5H1T-007** [comment]
> Ah nice. I think this makes sense. Wanna open a PR? We’ll double check then merge it

Sure I will open a PR for the same.

**Comment by H4R5H1T-007** [comment]
@okhat I have opened a PR as you mentioned.

**Comment by bakebrain** [comment]
Hey - I am running into the same error and additionally this one via transformers:

```
File [~/miniconda3/envs/colbert/lib/python3.8/site-packages/transformers/modeling_utils.py:118](https://file+.vscode-resource.vscode-cdn.net/Users/bakebrain/src/jobs_for_humanity/~/miniconda3/envs/colbert/lib/python3.8/site-packages/transformers/modeling_utils.py:118), in is_fsdp_enabled()
    117 def is_fsdp_enabled():
--> 118     return torch.distributed.is_initialized() and strtobool(os.environ.get("ACCELERATE_USE_FSDP", "False")) == 1

AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
```

M1 with arm64 python
