### ISSUE TITLE
Finetuning nway parameter

### ISSUE THREAD

**Issue by slawekgarcarz** [stanford-futuredata/ColBERT#245]
Hello,

Is it possible to set nway parameter in the config to a value higher than 2? When I tried using more examples per query for fine-tuning from provided ColBERTv2 checkpoint I'm getting following assertion error:

File "../colbert/training/lazy_batcher.py", line 69, in collate
    assert len(passages) == self.nway * self.bsize
AssertionError

**Comment by okhat** [comment]
Of course! But you need the json file to have enough negatives per line

**Comment by slawekgarcarz** [comment]
Oh, sorry. I get it now. Thank you!
