### ISSUE TITLE
what is  purpose of Sort by maxlens in tensorize_triples

### ISSUE THREAD

**Issue by fword** [stanford-futuredata/ColBERT#26]
hi, what is  purpose of Sort by maxlens in tensorize_triples . I don't think it is effective

indices = maxlens.sort().indices

  Q_ids, Q_mask = Q_ids[indices], Q_mask[indices]
  D_ids, D_mask = D_ids[:, indices], D_mask[:, indices]

 (positive_ids, negative_ids), (positive_mask, negative_mask) = D_ids, D_m

**Comment by okhat** [comment]
Hi! This is a small feature-in-progress. If you have large variation in document lengths and use gradient accumulation (i.e., pass --accum larger than 1), then sorting allows truncating some sub-batches to small sequence lengths, reducing training time. This truncation isn't applied yet, so sorting is like a no-op.
