### ISSUE TITLE
Clarification on PLAID retrieval

### ISSUE THREAD

**Issue by thibault-formal** [stanford-futuredata/ColBERT#263]
Hi @okhat and all!

In your PLAID paper (very nice btw!), I cannot understand the difference between ndocs/4 (which seems to be the number of documents after Stage 3) and k (which seems to be the number of documents to exactly re-rank in Stage 4). In the end, for how many documents true relevance scores are computed?
Thx in advance! 
Thibault

**Comment by thibault-formal** [comment]
Hey Omar! I hope you are well too! 
I see -- so basically 
* in the k=10 scenario, you compute 256/4=64 exact scores
* in the k=100 scenario, you compute 1024/4=256 exact scores
etc.

Just checking that I got things correctly, as I have been working on related stuff :)
Thanks

**Comment by okhat** [comment]
This sounds right, but @santhnm2 might be able to confirm too

**Comment by thibault-formal** [comment]
Perfect, thank you both for the quick answer!
