### ISSUE TITLE
Request for defining the command line parameters in more details

### ISSUE THREAD

**Issue by vikas95** [stanford-futuredata/ColBERT#27]
Hi @okhat, 

Thanks for sharing and maintaining the codes. I had a small clarification question regarding the command line parameters used while indexing - https://github.com/stanford-futuredata/ColBERT#indexing

We have to enter "--root" twice while indexing. Do we have to give the same directory as the experiment directory used while training ("/root/to/experiments/") for both the -root params?
It would be very helpful if a small description can be added for all the params used in training, validation, indexing and retrieval step. 

I am also getting this error -
 ColBERT/ColBERT-master/colbert/index.py", line 28, in main
   assert not os.path.exists(args.index_path), args.index_path
   
  which I believe can be solved once correct command line parameters are given. Do you have any suggestions on this?

  Thanks.

**Comment by okhat** [comment]
Hi Vikas,

Thank you for the feedback!

For all commands, you can pass `--root /path/to/experiments/` as a path where your experimental metadata and outputs will be stored. For indexing-related commands, you should _additionally_ pass `--index_root /path/to/indexes/`, which will contain (only) the index files. These two directories should be different. One way to do this is to use `<root>/indexes/` as your path.

As for the error:
```
ColBERT/ColBERT-master/colbert/index.py", line 28, in main
assert not os.path.exists(args.index_path), args.index_path
```

This just asserts that the directory of this index doesn't already exist. It avoids overwriting existing files. You can just `rmdir <index_root>/<index_name>`.

Let me know if you have any other questions!

**Comment by vikas95** [comment]
Hi Omar, 

Thanks for the quick response and clarification, I appreciate it.
