### ISSUE TITLE
Recall and MRR for checkpoint different from paper

### ISSUE THREAD

**Issue by Sheshansh** [stanford-futuredata/ColBERT#273]
I was evaluating ColBERTv2 on MS MARCO dev set with 6980 queries.
I am getting the following metrics using your provided model checkpoint.
MRR@10 = 39.6, Recall@1000 = 97.7 for end-to-end retrieval.

The ColBERTv2 paper says 
MRR@10 = 36.0, Recall@1000 = 96.8 for end-to-end retrieval.

Am I doing something wrong or is the checkpoint provided better than the version from paper?

**Comment by okhat** [comment]
You’re just reading the paper incorrectly. Please consult the table again in the colbertv2 paper.

**Comment by Sheshansh** [comment]
Thanks, just re-read. Oopsie.
