### ISSUE TITLE
How to see progress of Indexing 

### ISSUE THREAD

**Issue by meti-94** [stanford-futuredata/ColBERT#278]
I am currently using ColBERTv2 to create an information retrieval (IR) system for millions of facts presented in the form of sentences. The testing phase has worked well so far, but since I am facing limitations in resources, it is essential for me to monitor the progress of indexing. I was wondering if there is any way to track the progression, for instance, by elapsed or remaining time, or any other means available?

**Comment by okhat** [comment]
It currently prints out this information to the console. Is that visible on your end?

**Comment by meti-94** [comment]
I was able to observe the progress by adjusting the settings of my IPython notebook kernel. Thank you for providing such an excellent solution!
