### ISSUE TITLE
About training from scratch

### ISSUE THREAD

**Issue by Hannibal046** [stanford-futuredata/ColBERT#279]
Hi,

Thanks for the great idea and code! I want to train ColBERT from scratch and when following the instruction in README, I got the following error. Here is my procedure:

1. download all files with:

   ```bash
   wget https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz
   wget https://msmarco.blob.core.windows.net/msmarcoranking/fulldocuments.jsonl.gz
   wget https://msmarco.blob.core.windows.net/msmarcoranking/triples.train.small.tar.gz
   wget https://msmarco.blob.core.windows.net/msmarcoranking/top1000.dev.tar.gz
   wget https://msmarco.blob.core.windows.net/msmarcoranking/top1000.eval.tar.gz
   wget https://msmarco.blob.core.windows.net/msmarco/train_v2.1.json.gz
   wget https://msmarco.blob.core.windows.net/msmarco/dev_v2.1.json.gz
   wget https://msmarco.blob.core.windows.net/msmarco/eval_v2.1_public.json.gz
   gunzip eval_v2.1_public.json.gz
   gunzip fulldocuments.jsonl.gz
   gunzip dev_v2.1.json.gz
   gunzip train_v2.1.json.gz
   tar -xzvf top1000.eval.tar.gz
   tar -xzvf top1000.dev.tar.gz
   tar -xzvf triples.train.small.tar.gz
   tar -xzvf collectionandqueries.tar.gz
   rm *.gz
   ```

2. since there is no `queries.train.small.tsv`, I replace it with `queries.train.tsv`, here is my training script:

   ```python
   from colbert.infra import Run, RunConfig, ColBERTConfig
   from colbert import Trainer
   
   if __name__=='__main__':
       with Run().context(RunConfig(nranks=4, experiment="msmarco")):
   
           config = ColBERTConfig(
               bsize=32,
               root="experiments",
           )
           trainer = Trainer(
               triples="data/triples.train.small.tsv",
               queries="data/queries.train.tsv",
               collection="data/collection.tsv",
               config=config,
           )
   
           checkpoint_path = trainer.train()
   
           print(f"Saved checkpoint to {checkpoint_path}...")
   ```

3. and i got the following error:

   ![image](https://github.com/stanford-futuredata/ColBERT/assets/38466901/558a9caa-7027-4969-b754-6e2a0f4bab3c)
So my question is:

- According the instruction in README.md, the format for training is a JSONL triples file with a `[qid, pid+, pid-]`, where should I get these files since there is no `id` in `triples.train.small.tsv`
- According to the code in the README.md, the format for training is standard `MS Marco` tsv file, so where can I get `queries.train.small.tsv` and why is the error above?

Thanks for your reply!

**Comment by okhat** [comment]
For high level training, we recommend using RAGatouille now: https://github.com/bclavie/ragatouille

**Comment by Hannibal046** [comment]
Thanks for reply! I also write a project which seeks to provide the minimal implementation of ColBERT at [nanoColBERT](https://github.com/Hannibal046/nanoColBERT) just for concept of guide.  Please let me know if you are interested in it!

**Comment by okhat** [comment]
Wow that's amazing!

Do you need help advertising that? Do you have a Twitter account?

**Comment by Hannibal046** [comment]
Thank you so much for your kind words and your generous offer to help with advertising! I would definitely appreciate any assistance in spreading the nanoColBERT.

As for Twitter, you could find me `@NLPwithIR` but I'm not very active there.

**Comment by okhat** [comment]
Ah I see. Do you want to tweet your announcement tomorrow morning Pacific time? After 12-15 hours

**Comment by Hannibal046** [comment]
Sure. I would let you know as soon as I tweet

**Comment by okhat** [comment]
Hey @Hannibal046 , do you still want to announce this?

**Comment by Hannibal046** [comment]
Hi, thanks for your attention! I mentioned you the other day in twitter. Appreciate for advertising!
![image](https://github.com/stanford-futuredata/ColBERT/assets/38466901/d5cadc85-4d60-4cb7-8f8f-7fcaaec5f833)
