### ISSUE TITLE
low recall@1k

### ISSUE THREAD

**Issue by Hannibal046** [stanford-futuredata/ColBERT#280]
Hi, thanks for the great work. I am evaluating official checkpoint on the msmarco dev set accroding to README. And it seems there is some inconsistency part (98.4 on the paper) regarding to recall@1k. Could you please take time to check this?
![image](https://github.com/stanford-futuredata/ColBERT/assets/38466901/4b4fcd45-77fc-4b64-bf46-149457fc4b2b)

**Comment by okhat** [comment]
It just looks like you retrieved top 100, not top 1000. So your recall@1000 is just recall@100.

**Comment by Hannibal046** [comment]
Yeah, indeed. I set it to be 100 in `ranking = searcher.search_all(queries, k=100)`. I thought  it was 200, but I didn't find the number 200 using `Ctrl + F`. Haha, thanks for you prompt response and patience!
