### ISSUE TITLE
Hands On with Colab

### ISSUE THREAD

**Issue by finardi** [stanford-futuredata/ColBERT#3]
Hi, great article! The code looks very clean and understandable. Is it possible to make a Colab with tiny sample data.. With the pre-trained model.

**Comment by okhat** [comment]
Sounds like a great idea! I'm not super familiar with Colab, but it shouldn't be difficult. Thanks for suggesting this, Paulo.

**Comment by okhat** [comment]
Btw there are two really cool demos here: https://github.com/terrierteam/pyterrier_colbert

I believe they're already set up to use Colab!
