### ISSUE TITLE
Release checkpoints and datasets

### ISSUE THREAD

**Issue by joshdevins** [stanford-futuredata/ColBERT#33]
Just wondering if you can release "official" model checkpoints, ideally to the HuggingFace model repo (ideally both, also the model for TREC CAR trained only on the Wikipedia training set). It would also help experimentation (improve time to reproduce results) if you could also release datasets representing the document embeddings for MS MARCO Passages, TREC CAR (used in the paper) and even other common datasets ([Google Natural Questions](https://ai.google.com/research/NaturalQuestions)/[Wiki passages used in DPR](https://github.com/facebookresearch/DPR#resources--data-formats), for example).

Examples of similar releases include:
 * [docTTTTTquery](https://github.com/castorini/docTTTTTquery)
 * [DPR](https://github.com/facebookresearch/DPR)

**Comment by okhat** [comment]
Thanks for the feedback Josh!

I am happy to provide checkpoints that you can use---I generally provide them to anyone who asks! I think that maintaining a set of official model releases is also a great idea, but it may take some time to maintain this publicly with instructions. On the other hand, releasing embeddings seems really expensive though: where can one upload tens of GBs for possibly frequent downloads?

**Comment by joshdevins** [comment]
Do you think you can get the checkpoints up with supporting code on HuggingFace model hub (it's free, you can even [create an org for Stanford](https://huggingface.co/transformers/model_sharing.html#basic-steps))? I see [Vespa](https://huggingface.co/vespa-engine/colbert-medium) have theirs up but it might be nice to have the official one there. I noticed as well somewhere (maybe a closed issue?) that they also had to change the training procedure somehow to make it fit into Transformers. Happy to work with you on this if it helps.

The data hosting might be hard unless your university are willing to host it somewhere. I recall that docTTTTTquery is hosting assets on GitLab and Dropbox.

**Comment by okhat** [comment]
We've handled the checkpoints sharing by email.

For HuggingFace, I think it's cool but have mixed feelings about this. It would definitely ease experimentation with the model, but I don't how it will handle things like efficient indexing and retrieval. I'll check out Vespa or DPR on HuggingFace to see. We see this repository continuing to evolve (e.g., it will soon support multiple variants of ColBERT's late interaction paradigm) and I'm not sure how easy it will be to maintain two versions.

Ultimately, I think we can help with whatever you have in mind on this repo itself. Or is there something unique to HuggingFace?

**Comment by joshdevins** [comment]
HuggingFace Transformer integration would just make it easier for people to experiment outside of your repo and codebase. You would end up hosting your checkpoints on the model hub and implement the Transformer classes necessary to support ColBERT and variants. Training, data prep, etc. could still be in your repo of course, as well as evaluation and experimentation, but for people just wanting to do inference from a model checkpoint, Transformers is becoming the de-facto method (IMO).

**Comment by okhat** [comment]
This seems reasonable and will try to set it up. I'm closing here now as no immediate action is needed, but we can continue our email conversation.

**Comment by XY2323819551** [comment]
> We've handled the checkpoints sharing by email.
> 
> For HuggingFace, I think it's cool but have mixed feelings about this. It would definitely ease experimentation with the model, but I don't how it will handle things like efficient indexing and retrieval. I'll check out Vespa or DPR on HuggingFace to see. We see this repository continuing to evolve (e.g., it will soon support multiple variants of ColBERT's late interaction paradigm) and I'm not sure how easy it will be to maintain two versions.
> 
> Ultimately, I think we can help with whatever you have in mind on this repo itself. Or is there something unique to HuggingFace?



> We've handled the checkpoints sharing by email.
> 
> For HuggingFace, I think it's cool but have mixed feelings about this. It would definitely ease experimentation with the model, but I don't how it will handle things like efficient indexing and retrieval. I'll check out Vespa or DPR on HuggingFace to see. We see this repository continuing to evolve (e.g., it will soon support multiple variants of ColBERT's late interaction paradigm) and I'm not sure how easy it will be to maintain two versions.
> 
> Ultimately, I think we can help with whatever you have in mind on this repo itself. Or is there something unique to HuggingFace?

Hello，could I obtain the pre_trained ColModels？I cannot deal with such huge training dataset by my GPUs，but I want to do some deep research based on your pretrained ColBERT.

**Comment by XY2323819551** [comment]
> HuggingFace Transformer integration would just make it easier for people to experiment outside of your repo and codebase. You would end up hosting your checkpoints on the model hub and implement the Transformer classes necessary to support ColBERT and variants. Training, data prep, etc. could still be in your repo of course, as well as evaluation and experimentation, but for people just wanting to do inference from a model checkpoint, Transformers is becoming the de-facto method (IMO). Retrieval, indexing, etc. would remain in your repo or people (like me) would take care of it using different infrastructure (e.g. Elasticsearch or Vespa.ai for indexing and retrieval instead of FAISS). It would just make things more modular, so we can experiment. Think about it, maybe have a look through Transformers a bit more and see if it makes sense.

Hello，could you provide me with the pretrained ColBERT? 😊😊
