### ISSUE TITLE
be stuck with baseline reproduction

### ISSUE THREAD

**Issue by DreamsofGg** [stanford-futuredata/ColBERT#35]
I have reproduce the result of the final Colbert successfully. However, I am stuck with baseline reproduction which is [A], [B], [C] and [D] in the picture below. 
![image](https://user-images.githubusercontent.com/30079103/115958021-2c01d000-a538-11eb-8c5c-3eb323bb632a.png)
I wonder if you can give me some help like the source code of ablation study?

**Comment by okhat** [comment]
Duplicate, answered over email. Closing for now but feel free to re-open if needed.
