### ISSUE TITLE
Request: Adaptation for user-facing search application 

### ISSUE THREAD

**Issue by akinolawilson** [stanford-futuredata/ColBERT#36]
Thank you for sharing this incredible repo, great work!

Towards the end of your Readme file, you mention about providing pointers for the conversion of the code, especially [concerning the retrieval loop](https://github.com/stanford-futuredata/ColBERT/blob/4b7903c7b2327a5cd34477077c944f30986d5017/colbert/ranking/retrieval.py#L33), for when considering the model in a production environment. Are you able to provide any further details, such as what changes should be considered in this script for user-facing applications?

**Comment by okhat** [comment]
Thanks for the kind words, Akin!

Of course! Ultimately, the lines that run a query whose string is in the variable `q` are:

```
                Q = ranker.encode([q])
                pids, scores = ranker.rank(Q)
```

This returns the passage IDs and their scores.

The code above that sets up the `ranker` object, which depends on the `inference` object (which is prepared from the ColBERT checkpoint) and the `args` data (which is primarily, in this case, the path to the index).

Let me know if I can provide more help concerning these!

**Comment by okhat** [comment]
Is this resolved?

I will close it now but feel free to re-open if you have other questions.
