### ISSUE TITLE
args.milliseconds is always empty in ranking.py

### ISSUE THREAD

**Issue by aviclu** [stanford-futuredata/ColBERT#37]
Hi,

`args.milliseconds` is defined [here](https://github.com/stanford-futuredata/ColBERT/blob/abb5b684e4cda297f3ff58b52e70d5b90270e900/colbert/evaluation/ranking.py#L41) but never updated. It triggers a failure [here](https://github.com/stanford-futuredata/ColBERT/blob/abb5b684e4cda297f3ff58b52e70d5b90270e900/colbert/evaluation/ranking.py#L81), and thus the Avg Latency is missing and not computed.

**Comment by okhat** [comment]
Thanks---will fix in a little bit!

In any case, this is not the file you want to be timing. This script uses on-the-fly ranking which is (by nature) very slow.

Instead, you're probably more interested in the timing code of retrieval.py.

**Comment by aviclu** [comment]
@okhat Thanks for your quick reply!
In this case, how would you suggest running the test.py script in order to properly reproduce the validation results in your paper, including timing and latency results?

**Comment by okhat** [comment]
You can use colbert.index and colbert.retrieve/colbert.rerank if you're interested in low latency.

I just remove the offending line from colbert.test too if you don't want indexing or fast retrieval.

**Comment by aviclu** [comment]
Thanks! So, what is the most effective way to reproduce the results from Tables 1 and 2 from your paper?

**Comment by okhat** [comment]
For re-ranking, you need to use colbert.index and then colbert.rerank.

For end-to-end retrieval, you'll need colbert.index, colbert.index_faiss, and then colbert.retrieve.

**Comment by okhat** [comment]
Looks resolved?

Closing but feel free to re-open if I can help with other issues!
