### ISSUE TITLE
Can't build faiss index

### ISSUE THREAD

**Issue by JamesDeAntonis** [stanford-futuredata/ColBERT#38]
Thanks for the great repo!  I'm trying to build a faiss index for retrieval, but can't get the script to run.  I was originally using python3.8 and torch 1.8 in a docker container, but also downgraded to torch 1.6 to see if that would work.

I'm running
```
CUDA_VISIBLE_DEVICES="0,1" OMP_NUM_THREADS=1 \
python3.8 -m torch.distributed.launch --nproc_per_node=1 -m \
        index --root $PWD/experiments/ --amp --doc_maxlen 180 --mask-punctuation --bsize 256 \
        --checkpoint out-of-the-box-model.pt \
        --collection passages.tsv \
        --index_root /faiss --index_name INDEX \
        --root $PWD/experiments/ --experiment out_of_the_box \
        --local_rank 0
```

But I get the error "Default process group is not initialized".  That also happens even if I manually put `dist.init_process_group('nccl')` in the script.

Do you know why this is happening?

Thanks!

**Comment by okhat** [comment]
Another orthogonal thing is: do you want to index queries.tsv? Typically you'd want to index passages.

**Comment by JamesDeAntonis** [comment]
yes, they're passages.  The file is under a different name and i mistakenly put queries.tsv instead of passages.tsv

**Comment by JamesDeAntonis** [comment]
unfortunately, they still persist

what do you mean by initial indexing step?

**Comment by okhat** [comment]
I'm assuming this is the first step of indexing (before `colbert.index_faiss` is used).

If so, here's a sample script that's modified based on your command above:

```
CUDA_VISIBLE_DEVICES="0,1" OMP_NUM_THREADS=1 \
python -m torch.distributed.launch --nproc_per_node=2 -m \
colbert.index --root $PWD/experiments/ --amp --doc_maxlen 180 --mask-punctuation --bsize 256 \
--checkpoint out-of-the-box-model.pt \
--collection passages.tsv \
--index_root /faiss --index_name INDEX \
--root $PWD/experiments/ --experiment out_of_the_box \
```

Just to be sure: does this work for you?

**Comment by JamesDeAntonis** [comment]
(this the full error, btw)
<img width="1272" alt="Screen Shot 2021-05-07 at 8 24 18 AM" src="https://user-images.githubusercontent.com/33379057/117453443-f636f100-af12-11eb-8c96-e07663b5db83.png">

**Comment by JamesDeAntonis** [comment]
oh, and yes it's the first step (encoding)

**Comment by JamesDeAntonis** [comment]
I get this now (slightly different and may be a step in the right direction)
![Uploading Screen Shot 2021-05-07 at 9.06.14 AM.png…]()

**Comment by JamesDeAntonis** [comment]
I get this now (slightly different and may be a step in the right direction)
<img width="1017" alt="Screen Shot 2021-05-07 at 9 06 14 AM" src="https://user-images.githubusercontent.com/33379057/117453873-7198a280-af13-11eb-9159-e1a93e7f8e02.png">

**Comment by okhat** [comment]
Hmm this is strange. Could you run with one GPU in distributed mode and see if that works?

```
CUDA_VISIBLE_DEVICES="0" OMP_NUM_THREADS=1 \
python -m torch.distributed.launch --nproc_per_node=1 -m \
colbert.index --root $PWD/experiments/ --amp --doc_maxlen 180 --mask-punctuation --bsize 256 \
--checkpoint out-of-the-box-model.pt \
--collection passages.tsv \
--index_root /faiss --index_name INDEX \
--root $PWD/experiments/ --experiment out_of_the_box \
```

**Comment by JamesDeAntonis** [comment]
it didn't :/

**Comment by okhat** [comment]
Okay. What about single-GPU mode?

```
CUDA_VISIBLE_DEVICES="0" python -m \
colbert.index --root $PWD/experiments/ --amp --doc_maxlen 180 --mask-punctuation --bsize 256 \
--checkpoint out-of-the-box-model.pt \
--collection passages.tsv \
--index_root /faiss --index_name INDEX \
--root $PWD/experiments/ --experiment out_of_the_box \
```

**Comment by JamesDeAntonis** [comment]
ah yes, getting another error that I have already seen, and then it continues to hang (i saw this yesterday):
<img width="923" alt="Screen Shot 2021-05-07 at 9 13 55 AM" src="https://user-images.githubusercontent.com/33379057/117454878-98a3a400-af14-11eb-9be8-4e0b01debe0c.png">

**Comment by okhat** [comment]
Right, so you passages must be in a TSV file whose first column is the passage ID.

**Comment by JamesDeAntonis** [comment]
Great to know! I'll fix that

**Comment by okhat** [comment]
Okay, so single-GPU encoding will work.

For debugging the multi-GPU setup, could you run the following in a Python terminal?

```
import torch
torch.cuda.device_count()
```

**Comment by JamesDeAntonis** [comment]
1

**Comment by okhat** [comment]
Ah, so this all makes sense then. Either you only have one GPU or pytorch is not able to detect your other GPUs.

**Comment by JamesDeAntonis** [comment]
(I'm not sure why that is, by the way.  I have two GPUs)

**Comment by okhat** [comment]
Looks resolved?

Closing but feel free to reopen if I can help with other issues!
