### ISSUE TITLE
How to process data with tab?

### ISSUE THREAD

**Issue by chansonzhang** [stanford-futuredata/ColBERT#381]
Since colbert works with tab-separated file, e.g.
- Queries: each line is qid \t query text.
- Collection: each line is pid \t passage text.

I'm wondering if my passage text already has a "\t" in it? Will these cause error?
What's the recommend way to handle this?

**Comment by detaos** [comment]
If you don't escape it, yes it'll cause a parsing error.  You can either escape the character manually, or use a library to save the TSV file (which will do the escaping for you).

**Comment by chansonzhang** [comment]
> If you don't escape it, yes it'll cause a parsing error. You can either escape the character manually, or use a library to save the TSV file (which will do the escaping for you).

Thanks. By the way, I found I can directly pass a data dict to Queries
```
Queries(data={q_id:q for q_id,q in zip(query_ids,queries)})
```
But for index, I can't do it this way. So I escaped the character.
