### ISSUE TITLE
About validation

### ISSUE THREAD

**Issue by wangqian711** [stanford-futuredata/ColBERT#39]
1. In validation,top1000.dev dataset's format is qid,pid,query,passage?But in the load_topK_pids function,the label is passage?
2. assert qrels is None or topK_positives is None, "Cannot have both qrels and an annotated top-K file!" Can't qrels and topk exit at the same time?

**Comment by okhat** [comment]
Are you using colbert.test? This script has two different modes. One is to provide qrels and topk text (qid, pid, query, passage). The other is to provide topk (qid, pid, rank[, label] with optional label) and collection and queries.

Basically, I think you should drop --collection and --queries.

**Comment by wangqian711** [comment]
OK,Thank you for your reply!

**Comment by InhyeokYoo** [comment]
I actually don't understand.
If I use the first mode, than what is the topk text? Are passages in topk is all relevant? How can I give the labels which indicates passage is correct response for the query?

**Comment by InhyeokYoo** [comment]
> Are you using colbert.test? This script has two different modes. One is to provide qrels and topk text (qid, pid, query, passage). The other is to provide topk (qid, pid, rank[, label] with optional label) and collection and queries.
> 
> Basically, I think you should drop --collection and --queries.

I actually don't understand.
If I use the first mode, than what is the topk text? Are passages in topk is all relevant? Are they top 1000 results from BM25? How can I give the labels which indicates passage is correct response for the query?
