### ISSUE TITLE
train colbert with L2 similarity, but rerank with cosine similarity?

### ISSUE THREAD

**Issue by wuyaoxuehun** [stanford-futuredata/ColBERT#40]
As your paper has noted, you used L2 similarity during end to end retrieval, but in your code index_ranker->rank(), in the second stage of end-to-end retrieval, you rerank the passages with cosine similarity, here shoudn't you also use L2 similarity?
Thanks!

**Comment by okhat** [comment]
Good question! Short answer is that both of our similarity options are identical for ranking. They only differ with a linear transformation during training, but that has no impact on the order/ranking of the passages during retrieval.

Cosine is faster, so we use it consistently in retrieval.

**Comment by wuyaoxuehun** [comment]
> 
> 
> Good question! Short answer is that both of our similarity options are identical for ranking. They only differ with a linear transformation during training, but that has no impact on the order/ranking of the passages during retrieval.
> 
> Cosine is faster, so we use it consistently in retrieval.

Thanks! So train and rerank both use cosine similarity but index with faiss use L2, is this right?

**Comment by okhat** [comment]
This is a valid choice.

You can train with cosine or L2, both are good although not identical. I think the results are very close.

FAISS uses L2 internally and ranking uses cosine, yes, but that's okay because the vectors are normalized.

**Comment by okhat** [comment]
Closing as this seems resolved. But feel free to re-open if needed.
