### ISSUE TITLE
can't load full index into memory

### ISSUE THREAD

**Issue by JamesDeAntonis** [stanford-futuredata/ColBERT#42]
What's the easiest way to use `ColBERT` without loading the full index into memory?  We are building an index off of the `wiki_dpr` dataset (and eventually more), so we have about 21 million passages and counting.  The full index is about 630Gb on disk and we have 230Gb of memory to work with (hopefully not needing nearly the full 230).  I understand that faiss allows for this type of search (only metadata gets loaded into memory and the actual vectors stay on disk), so curious whether you support this in the current repo.

When running the retrieval script in the README, I run into memory issues once I start building `IndexPart` [here](https://github.com/stanford-futuredata/ColBERT/blob/3d64bf1540dcc4f641c40a83ddc1615985480406/colbert/ranking/rankers.py#L19).  Should I be doing something with the `index_part` param?  Any insight would be greatly appreciated.

Thanks!

(UPDATE: fyi, the retrieve script runs properly on a tiny dev subset of the dataset)

**Comment by okhat** [comment]
You just need to use batch-mode retrieval and ranking!

Just keep in mind it's two steps, not one. There are some instructions in the README. Let me know if you face issues using them.

**Comment by JamesDeAntonis** [comment]
Very cool!

By two-step, you're referring to how the second (re-ranking) step in end-to-end isn't implemented yet?  As suggested [here](https://github.com/stanford-futuredata/ColBERT/blob/3d64bf1540dcc4f641c40a83ddc1615985480406/colbert/ranking/batch_retrieval.py#L17)

**Comment by okhat** [comment]
The second step *is* implemented. You just need to use a different script `colbert.retrieve` then `colbert.rerank` (give it the output topk).

**Comment by okhat** [comment]
Precisely! Give it a run. It should be really fast and smooth, I hope :D

**Comment by JamesDeAntonis** [comment]
This seems to be working properly!

I am also having some pains due to trying to use [huggingface's model](https://huggingface.co/sebastian-hofstaetter/colbert-distilbert-margin_mse-T2-msmarco).  I noticed that in the paper it is said that the used output dimension is 128, and that is the default in this repo, but the HF pretrained model uses 768.  I plan to use 128 because I don't have space for 768, so I'll probably nix huggingface entirely, outside of how it's used in this repo.

Do you have the dim 128 model saved anywhere, as used in the paper?

**Comment by okhat** [comment]
Not sure if we corresponded about this by email, but as I mentioned to some other folks, I'm happy to share a checkpoint with you if you reach out by email!
