### ISSUE TITLE
Speeding up `FaissIndex` loading

### ISSUE THREAD

**Issue by JamesDeAntonis** [stanford-futuredata/ColBERT#52]
[This](https://github.com/stanford-futuredata/ColBERT/blob/master/colbert/ranking/faiss_index.py#L56) for-loop takes like 75 seconds for me, which is annoying to run every time I load the index.

I think we can shorten it by doing the following in the `index.sh` part of the pipeline:

```
total_num_embeddings = sum(all_doclens)
emb2pid = torch.zeros(total_num_embeddings, dtype=torch.int)
offset_doclens = 0

for pid, dlength in enumerate(all_doclens):
    emb2pid[offset_doclens: offset_doclens + dlength] = pid_offset + pid
    offset_doclens += dlength

torch.save(emb2pid, os.path.join(index_path, "emb2pid.pt")
```

and then in place of the current code in `faiss_index.py`:

```
emb2pids = torch.load(os.path.join(index_path, "emb2pid.pt")
if part_range is not None:
    emb2pids = emb2pids[emb2pids >= part_range.start]
    emb2pids = emb2pids[emb2pids < part_range.stop]

self.emb2pids = emb2pids
```

I think this would cut the time from 75 seconds to like 3 seconds, which would be a significant speedup

**Comment by okhat** [comment]
Awesome!

What is index.sh?

**Comment by okhat** [comment]
Also feel free to make a pull request if these are the changes.
