### ISSUE TITLE
Running/debugging ColBERT on CPU

### ISSUE THREAD

**Issue by littlewine** [stanford-futuredata/ColBERT#53]
Hello, 
I am trying to make some changes/adaptations in the code of ColBERT and I want to run locally on a MacBook without GPU.

However, when I am trying to create the index (`python -m colbert.index ...` ) I get 
`AssertionError: Torch not compiled with CUDA enabled`

On the other hand, when I generate the index on GPU , transfer it to my local machine and run `python -m colbert.index_faiss ...` I get:
```
[Jun 16, 14:29:18] #> Will write to /Users/amkrasakis/data/faiss_indexes/MSMARCO.L2.32x200k.180len.small/ivfpq.32768.faiss.
[Jun 16, 14:29:18] #> Loading /Users/amkrasakis/data/faiss_indexes/MSMARCO.L2.32x200k.180len.small/0.pt ...
[Jun 16, 14:29:24] #> Loading /Users/amkrasakis/data/faiss_indexes/MSMARCO.L2.32x200k.180len.small/1.pt ...
#> Sample has shape (2946381, 128)
[Jun 16, 14:29:25] #> Training with the vectors...
[Jun 16, 14:29:25] #> Training now (using 0 GPUs)...
Segmentation fault: 1
```

Is there some solution to that?
For instance, since colbert.index_faiss does not complain about no GPU (at least so far) could I generate the faiss index in a linux node with GPU and afterwards transfer this to another machine with FAISS cpu?

Thanks for your help!

**Comment by okhat** [comment]
I think some of these are probably about the dependencies, particularly torch and faiss.

Make sure you install the CPU versions of both, since our default dependencies are the GPU ones. Does this resolve the issue?
