### ISSUE TITLE
Indexing and retrieval arguments for ColBERT quantization

### ISSUE THREAD

**Issue by surajnair04** [stanford-futuredata/ColBERT#56]
Hi,

Thanks for releasing the code!
I am trying to replicate the MSMARCO DEV passage ranking results using the **quantization** branch but unable to do so.

Here's the set of commands I use to index:
```
CUDA_VISIBLE_DEVICES="0,1,2,3" OMP_NUM_THREADS=6 \
python -m torch.distributed.launch --nproc_per_node=4 -m \
colbert.index --amp --doc_maxlen 180 --mask-punctuation --bsize 256 --compress \
--checkpoint /path_to_checkpoint/colbert.dnn \
--collection /path_to collection/collection.tsv \
--index_root /path_to_index/indexes --index_name MSMARCO.psg.32x200k \
--root /path_to_root_dir/ --experiment MSMARCO-psg

python -m colbert.index_faiss \
--index_root /path_to_index/indexes --index_name MSMARCO.psg.32x200k \
--partitions 32768 --sample 0.3 \
--root /path_to_root_dir/ --experiment MSMARCO-psg
```

For end-to-end retrieval, I use the same command as in the README of the master branch

```
python -m colbert.retrieve \
--amp --doc_maxlen 180 --mask-punctuation --bsize 256 \
--queries /exp/scale21/data/multi-msmarco/source/queries.dev.small.tsv
--nprobe 32 --partitions 32768 --faiss_depth 1024 \
--index_root /path_to_index/indexes/ --index_name MSMARCO.psg.32x200k \
--checkpoint /path_to_checkpoint/colbert.dnn \
--root /path_to_root_dir/ --experiment MSMARCO-psg
```

@okhat Can you let me know if I'm missing some parameters specific to indexing or retrieval that I need to additionally incorporate? 

Thanks in advance,
Suraj

**Comment by okhat** [comment]
Hi Suraj! Thanks for the question.

I'll get back to you after a few meetings, but I wanted to mention a limitation of the "beta" quantization branch. FAISS indexing shouldn't be done over the compressed vectors; the double compression leads to very poor FAISS quality in that case.

**Comment by surajnair04** [comment]
Hi @okhat, thanks for your prompt response!
I think I understand what's happening
- the initial `colbert.index` step in the beta quantization branch compress the vectors
- `colbert.faiss_index` step would then further compress the vector as part of the underlying indexing strategy

This double compression leads to a drop in the ranking quality. Is this correct?

So, the alternative is to wait for the beta branch to stabilize at which point `colbert.index` would contain the FAISS indexing? 
Do you have a sense of when the release is planned? 
I'm quite eager to try it out :)

The commands are pretty much the same as in the master branch (with the exception of `--compress` argument for `colbert.index`)

**Comment by okhat** [comment]
> This double compression leads to a drop in the ranking quality. Is this correct?

Exactly. If you have the uncompressed index, you can create the FAISS object on top of that. Then this is resolved.

Otherwise, we're planning to update this in less than 2 weeks.

> The commands are pretty much the same as in the master branch (with the exception of --compress argument for colbert.index)

Yup sounds right to me

**Comment by surajnair04** [comment]
> Exactly. If you have the uncompressed index, you can create the FAISS object on top of that. Then this is resolved.
> 
> Otherwise, we're planning to update this in less than 2 weeks.
> 

I believe using an uncompressed index would make sense for smaller document collections from a storage perspective.
However, I am interested in storing the compressed vectors in FAISS so it makes sense to wait.

Thanks for your help, @okhat!

**Comment by okhat** [comment]
@surajnair04 It's ready, beta version: https://github.com/stanford-futuredata/ColBERT/tree/binarization

**Comment by surajnair04** [comment]
@okhat, Thanks a lot! I will try it out and open new issues if I encounter any.
Closing this one for now.
