### ISSUE TITLE
Long document/passage splitting in ColBERT

### ISSUE THREAD

**Issue by littlewine** [stanford-futuredata/ColBERT#59]
I would like to ask how/whether ColBERT handles long documents and whether there is any splitting etc. going on.

I think I've asked this question in the past @okhat and the response was negative (there's no handling whatsoever, its just matching on the first X tokens of the passage, depending on `doc_maxlen` - which is often set to `180`), but I can't fully remember and the following logs made me reconsider:

```
[Jul 21, 11:54:40] #> Processing batch #0..
[Jul 21, 11:54:40] #> Fetching parts 2--3 from queue..
[Jul 21, 11:54:49] #> Using strides [108, 180]..
```

In this case, what are the strides? I recognize that `180` as the `doc_maxlen`. Is this strictly practical and related to batching, or does it have to do something with document splitting?

thanks!

**Comment by okhat** [comment]
There's no automatic handling. You can use utility/preprocess/docs2passages to pre-process, though!

Strides are indeed a batching thing.
