### ISSUE TITLE
Effect Comparsion with Poly-Encoder for text match task

### ISSUE THREAD

**Issue by realize-qzq** [stanford-futuredata/ColBERT#60]
hi, I just wonder that ColBERT and[ Poly-Encoder ](https://arxiv.org/pdf/1905.01969.pdf)which is better for text match task (whether sentence pair is in same class)? Have you compared them? Thx!

**Comment by okhat** [comment]
Unlike Poly-Encoder, ColBERT mainly targets retrieval problems and is much more scalable to the maxsim design. I'm not aware of comparisons between the two on the problems you're referring to.
