### ISSUE TITLE
Question about scoring function

### ISSUE THREAD

**Issue by zhiqihuang** [stanford-futuredata/ColBERT#62]
Hi

Thanks for sharing the code. I have a question about score calculation.

In [doc](https://github.com/stanford-futuredata/ColBERT/blob/efaabb0f8731c7d96a9fe109a125357a9232f7a7/colbert/modeling/colbert.py#L49) function, the representation of the document is multiplied with the mask. 

However, could the `max(2)` in the [score](https://github.com/stanford-futuredata/ColBERT/blob/efaabb0f8731c7d96a9fe109a125357a9232f7a7/colbert/modeling/colbert.py#L61) function accidentally choose the padding token score (which score is 0) if all the non-padding token scores are negative?

I asked because I check the implementation [here](https://huggingface.co/sebastian-hofstaetter/colbert-distilbert-margin_mse-T2-msmarco) and found they assign a large negative value `score[~exp_mask] = - 10000` before search for the max score.

**Comment by okhat** [comment]
That's indeed a good edge case to keep in mind — thanks! Since we care about the largest/max similarities per query token for the high-scoring documents, these are practically always positive. But we might want to enforce this more directly with a ReLU before the max sim.

**Comment by zhiqihuang** [comment]
It is based on your similarity function. L2 is always positive, but cosine similarity could be negative. I agree with you that all negative similarities are definitely a concern case.
