### ISSUE TITLE
Index does not fit to RAM 

### ISSUE THREAD

**Issue by littlewine** [stanford-futuredata/ColBERT#64]
![image](https://user-images.githubusercontent.com/11770081/129848611-790b791e-1874-465e-a668-d5c365ae2ab1.png)
Hi,
I am trying to run inference (retrieve.py)in a quite big collection and I get the following error :

```
RuntimeError: [enforce fail at CPUAllocator.cpp:64]. DefaultCPUAllocator: can't allocate memory:you tried to allocate 664833940224 bytes. Error code 12 (Cannot allocate memory) 

```

To my understanding, that means that colbert requires 600+ gb of memory, which the machine does not have. Is there any way to bypass this issue?

Can I read the file from  an SSD and how much slower would the process be? 

Some colleagues also suggested using huggingface.co datasets for that but I'm unsure whether this is feasible or where to start!

**Comment by okhat** [comment]
Might want to use batch retrieval and batch re-ranking? Brief instructions are in the README.

It does search in two steps, but doesn't have to load the full index into memory.

**Comment by okhat** [comment]
Alternatively, you might be interested in our binarization branch. It makes the index much smaller. It's still a work in progress; we'll improve its quality in the next 2-3 weeks. (Until then, you might lose a couple of points of quality if you use the binarization branch.)

**Comment by okhat** [comment]
@littlewine Is this resolved?

**Comment by littlewine** [comment]
Yes indeed! Thanks for your help!

**Comment by Lim-Sung-Jun** [comment]
> Might want to use batch retrieval and batch re-ranking? Brief instructions are in the README.
> 
> It does search in two steps, but doesn't have to load the full index into memory.

Can you explain why you didn't add 512 in batch_retrieval?
