### ISSUE TITLE
Question on how are we storing in FAISS?

### ISSUE THREAD

**Issue by deepankar27** [stanford-futuredata/ColBERT#65]
Hello Team, 

Thanks a lot for sharing the code. :)

I am trying to understand how we are saving the embeddings of a document and let me know if my understanding is wrong.

Say, I have document _1/ passage with 10 words & after tokenization it gives me 15 tokens so, my final embeddings would be [1,15,128] considering I have set compressed dim = 128.
While storing this final embeddings we are doing two level of quantization on every context word embeddings & then saving it to FAISS but are we saving it in batch wise like all 15 embeddings will be stored against some batchidx?

I am still learning how FAISS works so, I am really sorry if I have asked an amateur question.

**Comment by okhat** [comment]
Hey @deepankar27 !

In our faiss representations, we store a flat matrix indeed. So we'll store 15 embeddings. If you had two documents, one with 15 tokens and the other with 20 tokens, we'll feed faiss a matrix with shape (15+20, 128).

Hope this helps! Let me know if you have any other questions.

**Comment by deepankar27** [comment]
Hello, @okhat  thanks a lot for the response. I understood your explanation. I believe that's why we are wrote this code in : 

https://github.com/stanford-futuredata/ColBERT/blob/49d7fb69bdb2d7340780bad2926b06f6ce14d928/colbert/ranking/faiss_index.py#L76
  
This lead to only few last questions:
1.  If my understanding is correct then are we storing these embeddings against emb2pid?
     self.emb2pid[offset_doclens: offset_doclens + dlength] = pid_offset + pid
     https://github.com/stanford-futuredata/ColBERT/blob/49d7fb69bdb2d7340780bad2926b06f6ce14d928/colbert/ranking/faiss_index.py#L57
2. Are we performing two level of quantization for Query embeddings as well?

**Comment by okhat** [comment]
Dropping stopwords is fine in practice, indeed!

emb2pid is just a mapping from each embedding to its document of origin.

Queries are not compressed with FAISS.

**Comment by deepankar27** [comment]
@okhat Thanks and appreciate your responses :clap:
