### ISSUE TITLE
TREC-CAR pre-trained model in PyTorch

### ISSUE THREAD

**Issue by cramraj8** [stanford-futuredata/ColBERT#68]
I am trying to look at TREC-CAR data and its pre-trained model on Wikipedia training set. However, the [previous work](https://github.com/nyu-dl/dl4marco-bert) that provides the pre-trained model only in Tensorflow. Did you have to convert the Tensorflow checkpoint files into PyTorch to train your model on top ?

**Comment by okhat** [comment]
Yes indeed. 

This might help.  https://github.com/huggingface/transformers/blob/master/src/transformers/models/bert/convert_bert_original_tf_checkpoint_to_pytorch.py

**Comment by cramraj8** [comment]
Thanks! this is helpful.
