### ISSUE TITLE
are the pretrained weights released publicly? 

### ISSUE THREAD

**Issue by dingusagar** [stanford-futuredata/ColBERT#70]

**Comment by okhat** [comment]
Apologies for the slow response. I share weights with folks who reach out via email; feel free to email me.

But we'll make a public release of multiple pretrained models in the next two weeks.

**Comment by jordane95** [comment]
Have you released your pretrained models? I still can't find any...

**Comment by okhat** [comment]
You can use the ColBERTv2 model / weights from the Jupyter notebook instructions on: https://github.com/stanford-futuredata/ColBERT/tree/new_api
