### ISSUE TITLE
Train for retrieval

### ISSUE THREAD

**Issue by DeepakSaini119** [stanford-futuredata/ColBERT#71]
Hi, thanks for the wonderful work and clean code. I wanted to understand how to train in case we don't have negative passages for queries. Would getting negatives from BM25 work well?

**Comment by okhat** [comment]
Apologies for the slow response. What you describe is a pretty standard approach indeed. You could then use the model you trained to sample even harder negatives, and then re-train with those.

Or you could sample the initial negatives with an off-the-shelf ColBERT model.

**Comment by okhat** [comment]
Closing this, but please let us know if you have any further questions!
