### ISSUE TITLE
ColBERT + BPR

### ISSUE THREAD

**Issue by crystina-z** [stanford-futuredata/ColBERT#72]
Hi! Just wonder if there is a more detailed description available on the trials on binarized ColBERT in [this](https://github.com/stanford-futuredata/ColBERT/tree/binarization#preliminary-results) section? I see it says an update is planned on August, but not sure if I found it online. Thanks!

**Comment by okhat** [comment]
Thanks for reaching out! We pushed back our plans a bit as we developed a much stronger compression methods for ColBERT, which is [for now] available here: https://github.com/stanford-futuredata/ColBERT/tree/new_api

With two bits per dimension, it preserves the full quality of the model in most of our tests. We'll release the results and details around mid November.

**Comment by crystina-z** [comment]
Hi @okhat thanks for the prompt reply! The results sound really amazing. Looking forward to read the full version! I'll read the `new_api` and close this issue for now.
