### ISSUE TITLE
clarification on the format for ranking.tsv

### ISSUE THREAD

**Issue by puzzlecollector** [stanford-futuredata/ColBERT#75]
@okhat 
Upon running the following command for retrieval:  
```
!python -m colbert.retrieve --amp --doc_maxlen 512 --query_maxlen 180 \
--mask-punctuation --bsize 128 \
--queries queries.tsv --partitions 32768 \
--index_root ./experiments/indexes \
--index_name test_index \
--checkpoint ./experiments/patents/train.py/2021-11-11_08.12.57/checkpoints/colbert.dnn
```
It appears that this command creates a ranking.tsv file.  The ranking.tsv file is of the following format 

<img width="1263" alt="Screen Shot 2021-11-15 at 1 49 17 PM" src="https://user-images.githubusercontent.com/15623464/141724211-8033be0f-6d7f-450d-bf94-5044315f7b6e.png">

From my understanding, it displays the query id, the id of the document in the collection (corpus) and the rank. And it seems like it only displays the top 1000 ranks. Is this correct?  So for example, in that screenshot, for query 0, document 45934 is ranked first (i.e. document 45934 is predicted to be the most similar to query 0)

**Comment by okhat** [comment]
Yes!

**Comment by okhat** [comment]
Closing. Feel free to re-open if you have more questions!
