### ISSUE TITLE
RuntimeError: Broken pipe

### ISSUE THREAD

**Issue by chenhuawei2019** [stanford-futuredata/ColBERT#79]
Hello, 
Thanks for your code, I really benefit a lot from it.
I have a question, I want to solve the error of "RuntimeError: Broken pipe".
But I can't find where defined the "num_workers", would you please tell me?
Thank you very much!

**Comment by okhat** [comment]
Hey @chenhuawei2019 ! What command leads to this error?

**Comment by chenhuawei2019** [comment]
@okhat 
Thanks for your reply! 
【CUDA_VISIBLE_DEVICES="0,1,2,3" \
python -m torch.distributed.launch --nproc_per_node=4 -m \
colbert.train --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
--triples /path/to/MSMARCO/triples.train.small.tsv \
--root /root/to/experiments/ --experiment MSMARCO-psg --similarity l2 --run msmarco.psg.l2】

I find the solution on the internet about "RuntimeError: Broken pipe". Some ways tell me to modify the "num_workers", but
I don't find where is it.

**Comment by okhat** [comment]
Ah okay, how many GPUs do you have? How much (CPU) memory do you have?

**Comment by chenhuawei2019** [comment]
> Ah okay, how many GPUs do you have? How much (CPU) memory do you have?

**Comment by chenhuawei2019** [comment]
@okhat I have 4 GPUs(15g) and my CPU memory is 128g, video memory is 16g.

**Comment by okhat** [comment]
Hey @chenhuawei2019 did you intend to close this issue?

**Comment by okhat** [comment]
Feel free to re-open the issue. I am unable to see the cause of your error. Is there a longer/full error message you can share?

**Comment by chenhuawei2019** [comment]
@okhat Thanks for your patient! This issue was caused by some other easy issues, but I didn't deal with them first so that I put this question, now  I have solved this well. Thanks for your patient again!
