### ISSUE TITLE
v2 code?

### ISSUE THREAD

**Issue by ArthurCamara** [stanford-futuredata/ColBERT#80]
Just received the email from Arxiv digest about v2. That looks great! 
Is it equivalent to 0.2 here? (I assume no) if no, do you have plans on releasing the code for that?
Thanks!

**Comment by okhat** [comment]
Thanks for reaching out! Most of the code has been on the new_api branch for the last couple of months.

https://github.com/stanford-futuredata/ColBERT/tree/new_api

**Comment by okhat** [comment]
It comes with a new, much easier-to-use pythonic API. But it's not very well-documented yet.
