### ISSUE TITLE
Influence of [SEP] token

### ISSUE THREAD

**Issue by namespace-Pt** [stanford-futuredata/ColBERT#83]
Hi, I noticed that in the paper you didn't add `[SEP]` token at the tail of query/document. Did you observe any performance difference with/without it?  I also wonder the effect of `[Q]` and `[D]` token.

**Comment by okhat** [comment]
We do in fact keep the [SEP] tokens! Sorry if this wasn't clear in the text.

That said, with very large training sets, the model can easily adjust to these minor differences in principle. [Q] and [D] serve to differentiate queries and documents for the model. But they're definitely not essential if you have a large training set where queries and documents look very different already. The model can learn to guess correctly.

**Comment by namespace-Pt** [comment]
Thank you!
