### ISSUE TITLE
Question about reranking procedure

### ISSUE THREAD

**Issue by puzzlecollector** [stanford-futuredata/ColBERT#84]
I'd like to know if my understanding of the reranking procedure is correct (my understanding of FAISS is very basic, but I am aware that it is a very optimized library for vector similarity search). 

1. I use a trained ColBERT to calculate the embeddings of the documents 
2. I index the calculated vectors of the documents 
3. When the query comes in I calculate the query embedding. After that I get all documents with document embeddings that are nearby the query embedding. FAISS is used in this process to get M such candidate documents. 
4. Once we get these M candidate documents, we use ColBERT to calculate the score of (q_emb, d_emb_i) where i = 1,...,M. Once the score is calculated, we rank the candidate documents based on the calculated score. 
5. We display the top K candidate documents with the highest calculated score.

**Comment by okhat** [comment]
That's exactly right. Apologies for the delay in my response.
