### ISSUE TITLE
Reranking Evaluation

### ISSUE THREAD

**Issue by namespace-Pt** [stanford-futuredata/ColBERT#85]
I noticed that in the official `dev1000` file, some queries (about 1000) don't have ground truth passage included. I'd like to know if you removed these queries or not when reporting results?

**Comment by okhat** [comment]
We never filter queries based on recall.

The official dev top-1000 results come from BM25, which has low recall. When we evaluate BM25 re-ranking, all systems get 0.0 for these queries. When we evaluate end-to-end retrieval, a system like ColBERT may or may not be able to improve quality on these queries.

**Comment by namespace-Pt** [comment]
Got it. Thank you. Successfully reproduced your reranking result based on the paper.
