### ISSUE TITLE
Colbert for text classification

### ISSUE THREAD

**Issue by kaushicaravind2000** [stanford-futuredata/ColBERT#86]
I have been trying to classify the document into suicidal or not. The document has 2 columns, 1 the tweet and the other is the label mentioning if its suicidal or not. Need help in training the model , building a saved model to get the doc and classify it. Currently I'm using the humour detection saved model on the suicidal detection and the accuracy is no more than 60%. Kindly help on this issue. Thank you in advance

**Comment by okhat** [comment]
Are you sure this issue pertains to the ColBERT retrieval model? I think you might be referring to another work on humor detection.

**Comment by kaushicaravind2000** [comment]
I'm not sure about the model. But I'm in search of a text classifier using
ColBert for suicidal Ideation Detection. Will this model help me? I'm stuck
in this for 2 weeks and I can share you my code too. Can you please help me
with this sir? Would be really appreciable

**Comment by okhat** [comment]
I suspect you're thinking about this paper by other authors: https://arxiv.org/abs/2004.12765

Our models can't do classification unfortunately. They do search.

**Comment by kaushicaravind2000** [comment]
Yes. I'm referring to this. Yes sir got it. Working on classifying the
texts. If you have any inputs and suggestions on how to go about it, please
let me know. Will be of great help. Really working hard for this. Any clue
or help will suffice.

**Comment by okhat** [comment]
You might want to check out the models on the HuggingFace transformers. You might need training data for your task.

In any case, I don't think ColBERT retrieval (our work) can help with this particular task.
