### ISSUE TITLE
How to train a ColBERT Re-ranker

### ISSUE THREAD

**Issue by KristenZHANG** [stanford-futuredata/ColBERT#87]
Hi, I want to train a ColBERT as a re-ranker on another dataset and want to seek some suggestions on it. 

My current method:
   
_I have a retriever model A, and for each query it reports Top-K (e.g. 50, 100) passages. Assume there are M queries, then I transfer the Top-K passages corresponding to M queries into around ~M*(K-1) triples:**<query, pos_psg, neg_psg>**. And then I use the ~M*(K-1) triples to train a ColBERT re-ranker_.

_On the one hand, the Top-K passages returned by a retriever can be viewed as hard negatives (exclusive ground-truth) and can let the model to learn to distinguish between the ground-truth and similary passages. On the other hand, although not labeled as ground-truth, the top few (e.g. 5) results returned by a retriever might also be related to the query if the retriever is strong enough._

Thus, I wan to ask whether this is a reasonable training strategy or any suggestions on how to better train a re-ranker based on a retriever's results.

Thanks!

**Comment by okhat** [comment]
This approach is generally reasonable. Selecting a large enough K (e.g., K = 200 or K = 500) typically reduces the risk [or, rather, reduces the frequency] of false negatives in the triples. This tends to work well enough in practice.

If you want to maximize quality, though, the emerging standard approach for dealing with false negatives [and also false positives] is to use distillation from a strong teacher model, often a cross-encoder or a ColBERT model. This teacher model itself is trained with triples as you described. Some useful references on this include our ColBERTv2 paper as well as the papers of Margin-MSE, RocketQAv2, and SPLADEv2.

**Comment by KristenZHANG** [comment]
Thanks so much for your advice! I'll look at the ColBERTv2 and try more possibilities.

**Comment by r1ckC139** [comment]
Hi @okhat,
Can you explain for me what are false negatives (and false positives) mean in context you mention above. If i have a dataset consists question and answer pairs, so in this case each question have only 1 positive answer. If i use BM25 to search negatives for each question, i just need remove answer (from BM25 result) that matches positive answer, then there will be no case of false negative right ? or false negatives are just negatives not  not challenging enough ?
