### ISSUE TITLE
Is it possible to do a classification with ColBERT?

### ISSUE THREAD

**Issue by nirmal2k** [stanford-futuredata/ColBERT#89]
Given a query and a document pair, is it possible to tell if the pair is positive or negative? Or does it only give scores which could be compared with other pairs?

**Comment by okhat** [comment]
Sorry for the delay, I just noticed this!  Your second statement is correct: the scores are continuous. You could in principle tweak your own standard for positive, negative, and a middle "gray area" depending on manual exploration or using some validation data. That said, relevance tends to be a continuous scale and is rarely binary in practice, so it can be hard to find perfectly calibrated scores.
