### ISSUE TITLE
Location of collections.tsv, queries.train.small.tsv files

### ISSUE THREAD

**Issue by sundavid2002** [stanford-futuredata/ColBERT#91]
Where can I find the collections.tsv and the queries.train.small.tsv files? They aren't on the MS MARCO Passage Ranking page.

**Comment by okhat** [comment]
You might have to download a tar.gz file called collectionandqueries, or something like that.

Let me know if you can't find it.

**Comment by okhat** [comment]
wget https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz 

This should work.

That said, you might find the Jupyter notebook on the new_api code easier to work with. It contains a model checkpoint for ColBERTv2 also.

**Comment by cuongdinh2021** [comment]
Hi Okhat, I ran into the same issue. In the link you sent, there are queries.dev.small.tsv and queries.eval.small.tsv but **no** queries.train.small.tsv file. Should queries.train.tsv be used instead of queries.train.small.tsv then?
