### ISSUE TITLE
Where is the k-means clustering code?

### ISSUE THREAD

**Issue by jordane95** [stanford-futuredata/ColBERT#92]
Hello, I read your ColBERTv2 paper. And I'm very impressed by the analysis of ColBERT's semantic space. I think it may be the main intuition to compresse the residual. But I can't find the corresponding code for it in your repo. Would you mind providing the code? Thank you!

**Comment by okhat** [comment]
Thanks for the kind words! Make sure you're checking the new_api branch.

Here, in particular:  https://github.com/stanford-futuredata/ColBERT/blob/378001bcc439cb3ed2d8935473c368604a7dd46e/colbert/indexing/collection_indexer.py#L146

**Comment by jordane95** [comment]
Hello again, I read your code but got a little confused.
To be more specific, in this [snnipet](https://github.com/stanford-futuredata/ColBERT/blob/new_api/colbert/indexing/collection_indexer.py#L82-L123). Is the kmeans clustering performed on a subset of randomly sampled passages rather than the whole dataset?

**Comment by okhat** [comment]
That's correct! This is also mentioned in the paper.

We must sample, otherwise we'd have to fit the entire uncompressed index in memory which defies our goal of compression.

**Comment by jordane95** [comment]
Thanks for your timely answer! I also see it in the paper.
But I don't quiet understand your explanation for this. I think that the sampling operation mainly reduces the number of centroids learned by kmeans, compared to non-sampling one (also the cost during indexing process). We still need to index/compresse the whole dataset, but with less number of centroids.
I don't see any conflict with the compression goal (except the cost of storing centroids). Could you explain it more preciously?
