### ISSUE TITLE
About beir evaluation

### ISSUE THREAD

**Issue by jordane95** [stanford-futuredata/ColBERT#96]
Hi,
I have a little question about your evaluation.
Your model is trained on MS MARCO, where the passage in `collection.tsv` only contains one field. As depicated in your paper, you prepend it with a special [D] token before feeding into BERT.
However for datasets in BEIR, passage in `corpus.jsonl` also contains a `title` field besides the `text` field.
May I know how did you evaluate your ColBERT on BEIR benchmark? In other words, how did you handle the `title` and `text` field?

**Comment by okhat** [comment]
Our code handles titles in collections: just make sure your collection.tsv has `pid \t text \t title` per line.

With this input, passages are fed to the encoder in the format `Title | Text`. This applies to BEIR and other datasets alike.
