### ISSUE TITLE
Solve syntax errors when training Colbert

### ISSUE THREAD

**Issue by poorya2021** [stanford-futuredata/ColBERT#98]
Hello @okhat 
I want to train Colbert on a specific dataset, but when I run the following code:

```
CUDA_VISIBLE_DEVICES="0" \
  python -m /lib/site-packages/torch.distributed.launch --nproc_per_node=1 -m /lib/site-packages/colbert.train \
  --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
  --triples /Dataset/Triple_for_train/colbert_train_triple.tsv
```
or
```
CUDA_VISIBLE_DEVICES="0" \
  python -m torch.distributed.launch --nproc_per_node=1 -m colbert.train \
  --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
  --triples /Dataset/Triple_for_train/colbert_train_triple.tsv
```

I get this error:

Error:
```
Input In [21]
    python -m /lib/site-packages/torch.distributed.launch --nproc_per_node=1 -m /lib/site-packages/colbert.train \
    ^
SyntaxError: cannot assign to operator
```

How can I solve this problem?
Thank you.

**Comment by okhat** [comment]
I'd navigate to the directory that contains the `colbert/` folder and then run:

```
CUDA_VISIBLE_DEVICES="0" \
  python -m torch.distributed.launch --nproc_per_node=1 -m colbert.train \
  --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
  --triples /Dataset/Triple_for_train/colbert_train_triple.tsv
```

Does this not work for you?

**Comment by poorya2021** [comment]
No, It`s not work
and I get this error:

```
python -m torch.distributed.launch --nproc_per_node=1 -m colbert.train \
^
SyntaxError: invalid syntax
```
I use python 3.8 and jupyter notebook

**Comment by okhat** [comment]
Oh, I see. You're running this inside a Jupyter notebook.

In that case, just add `!` before the command.

```!python -m torch.distributed.launch --nproc_per_node .....```

**Comment by poorya2021** [comment]
Thank you Omar
I had forgotten ```!```
I ran this part of the command (``` CUDA_VISIBLE_DEVICES="0" ``` )in one cell and the rest of the command in another cell
``` 
!python -m torch.distributed.launch --nproc_per_node=1 -m colbert.train \
--amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
--triples /Dataset/Triple_for_train/colbert_train_triple.tsv 
```
But now I have the following error:
```
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 10180) of binary: C:\ProgramData\Anaconda3\python.exe 
```

I tried to initialize the init_process_group with the following command:
``` 
dist.init_process_group('gloo', init_method='file:///C:/init/some_file', rank=0, world_size=1) 
```

But the error was not fixed.

Do you have any solution?

Thanks for your reply

**Comment by okhat** [comment]
```!python -m colbert.train \
--amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
--triples /Dataset/Triple_for_train/colbert_train_triple.tsv 
```

This should work, since you're using one GPU.

**Comment by poorya2021** [comment]
Thank you for your reply
The problem was solved.

**Comment by poorya2021** [comment]
Hi again @okhat 
I tried to train the model using my dataset, but in 5 minutes, the model will be trained. I use a Persian dataset. Do you think this is a reasonable amount of time to train the model?

My train file contains 18,000 queries, for each query there is a positive passage and some negative passages. Since the number of negative passages per query is more than one, I have put the negative passages of each query in a list. Is it okay to use the list in this case?


RAM: 54GB
GPU: RTX 2080 with 12 GB
